
class Main extends Window
{
	var tags; //KAGParser
	function Main () 
	{
		super.Window();
		initialize(DEConfig.device.width,DEConfig.device.height);

		this.tags = new TagHandlers(this);
		this.world = new GameWorld();
	}


	var _world=void;
	property world
	{
		setter(v){
			if (_world)
			{
				invalidate _world;
			}
			_world = v;
			Application.world = v;
		}
		getter{
			return _world;
		}
	}
}