
class SoundBuffer extends Audio
{
	function SoundBuffer () 
	{
		super.Audio();
	}

	function preload (path) 
	{
		return super.preload(getExistSoundPath(path));
	}
}

class BGMBuffer extends SoundBuffer
{
	function BGMBuffer () 
	{
		super.SoundBuffer();
	}

	function play (loop=true,fade=true) 
	{
		super.play(...);
	}
}

class SEBuffer extends SoundBuffer
{
	var buf=0;
	function SEBuffer () 
	{
		super.SoundBuffer();
	}

	function play (loop=false,fade=false) 
	{
		super.play(...);
	}
}