// generated from gentext.pl Messages.xlsx
#ifndef __STRING_TABLE_JP_H__
#define __STRING_TABLE_JP_H__
#define IDS_TJS_INTERNAL_ERROR_                                                    L"内部エラ_が_生しました"
#define IDS_TJS_WARNING_                                                           L"警告: "
#define IDS_TJS_WARN_EVAL_OPERATOR_                                                L"グロ_バルでない_所で後置 ! 演算子が使われています(この演算子の__はTJS2 version 2.4.1 で_わりましたのでご注意ください)"
#define IDS_TJS_NARROW_TO_WIDE_CONVERSION_ERROR_                                   L"文字列を UNICODE 文字列に__できません。解_できない文字が含まれてます。正しいデ_タが指定されているかを__してください。デ_タが破_している可能性もあります"
#define IDS_TJS_VARIANT_CONVERT_ERROR_                                             L"%1 から %2 へ型を__できません"
#define IDS_TJS_VARIANT_CONVERT_ERROR_TO_OBJECT_                                   L"%1 から Object へ型を__できません。Object 型が要求される文_で Object 型以外の_が渡されるとこのエラ_が_生します"
#define IDS_TJS_IDEXPECTED_                                                        L"__子を指定してください"
#define IDS_TJS_SUBSTITUTION_IN_BOOLEAN_CONTEXT_                                   L"_理_が求められている_所で = 演算子が使用されています(== 演算子の__いですか？代入した上でゼロと_を比_したい_合は、(A=B) != 0 の形式を使うことをお_めします)"
#define IDS_TJS_CANNOT_MODIFY_LHS_                                                 L"不正な代入か不正な式の操作です"
#define IDS_TJS_INSUFFICIENT_MEM_                                                  L"メモリが足りません"
#define IDS_TJS_CANNOT_GET_RESULT_                                                 L"この式からは_を得ることができません"
#define IDS_TJS_NULL_ACCESS_                                                       L"null オブジェクトにアクセスしようとしました"
#define IDS_TJS_MEMBER_NOT_FOUND_                                                  L"\"メンバ \"\"%1\"\" が_つかりません\""
#define IDS_TJS_MEMBER_NOT_FOUND_NO_NAME_GIVEN_                                    L"メンバが_つかりません"
#define IDS_TJS_NOT_IMPLEMENTED_                                                   L"呼び出そうとした_能は未_装です"
#define IDS_TJS_INVALID_PARAM_                                                     L"不正な引数です"
#define IDS_TJS_BAD_PARAM_COUNT_                                                   L"引数の数が不正です"
#define IDS_TJS_INVALID_TYPE_                                                      L"_数ではないかプロパティの__が_います"
#define IDS_TJS_SPECIFY_DIC_OR_ARRAY_                                              L"Dictionary または Array クラスのオブジェクトを指定してください"
#define IDS_TJS_SPECIFY_ARRAY_                                                     L"Array クラスのオブジェクトを指定してください"
#define IDS_TJS_STRING_DEALLOC_ERROR_                                              L"文字列メモリブロックを解放できません"
#define IDS_TJS_STRING_ALLOC_ERROR_                                                L"文字列メモリブロックを_保できません"
#define IDS_TJS_MISPLACED_BREAK_CONTINUE_                                          L"\"\"\"break\"\" または \"\"continue\"\" はここに_くことはできません\""
#define IDS_TJS_MISPLACED_CASE_                                                    L"\"\"\"case\"\" はここに_くことはできません\""
#define IDS_TJS_MISPLACED_RETURN_                                                  L"\"\"\"return\"\" はここに_くことはできません\""
#define IDS_TJS_STRING_PARSE_ERROR_                                                L"文字列定数/正_表_/オクテット即_が_わらないままスクリプトの_端に_しました"
#define IDS_TJS_NUMBER_ERROR_                                                      L"数_として解_できません"
#define IDS_TJS_UNCLOSED_COMMENT_                                                  L"コメントが_わらないままスクリプトの_端に_しました"
#define IDS_TJS_INVALID_CHAR_                                                      L"不正な文字です : \'%1\'"
#define IDS_TJS_EXPECTED_                                                          L"%1 がありません"
#define IDS_TJS_SYNTAX_ERROR_                                                      L"文法エラ_です(%1)"
#define IDS_TJS_PPERROR_                                                           L"条件コンパイル式にエラ_があります"
#define IDS_TJS_CANNOT_GET_SUPER_                                                  L"ス_パ_クラスが存在しないかス_パ_クラスを特定できません"
#define IDS_TJS_INVALID_OPECODE_                                                   L"不正な VM コ_ドです"
#define IDS_TJS_RANGE_ERROR_                                                       L"_が__外です"
#define IDS_TJS_ACCESS_DENYED_                                                     L"_み_み_用あるいは_き_み_用プロパティに_して行えない操作をしようとしました"
#define IDS_TJS_NATIVE_CLASS_CRASH_                                                L"_行コンテキストが_います"
#define IDS_TJS_INVALID_OBJECT_                                                    L"オブジェクトはすでに__化されています"
#define IDS_TJS_CANNOT_OMIT_                                                       L"\"\"\"...\"\" は_数外では使えません\""
#define IDS_TJS_CANNOT_PARSE_DATE_                                                 L"不正な日付文字列の形式です"
#define IDS_TJS_INVALID_VALUE_FOR_TIMESTAMP_                                       L"不正な日付__刻です"
#define IDS_TJS_EXCEPTION_NOT_FOUND_                                               L"\"\"\"Exception\"\" が存在しないため例外オブジェクトを作成できません\""
#define IDS_TJS_INVALID_FORMAT_STRING_                                             L"不正な_式文字列です"
#define IDS_TJS_DIVIDE_BY_ZERO_                                                    L"0 で除算をしようとしました"
#define IDS_TJS_NOT_RECONSTRUCTIVE_RANDOMIZE_DATA_                                 L"乱数系列を初期化できません(おそらく不正なデ_タが渡されました)"
#define IDS_TJS_SYMBOL_                                                            L"__子"
#define IDS_TJS_CALL_HISTORY_IS_FROM_OUT_OF_TJS2SCRIPT_                            L"[TJSスクリプト管理外]"
#define IDS_TJS_NOBJECTS_WAS_NOT_FREED_                                            L"合_ %1 _のオブジェクトが解放されていません"
#define IDS_TJS_OBJECT_CREATION_HISTORY_DELIMITER_                                 L"\n                     "
#define IDS_TJS_OBJECT_WAS_NOT_FREED_                                              L"オブジェクト %1 [%2] が解放されていません。オブジェクト作成_の呼び出し履_は以下の通りです:\n                     %3"
#define IDS_TJS_GROUP_BY_OBJECT_TYPE_AND_HISTORY_                                  L"オブジェクトのタイプとオブジェクト作成_の履_による分_"
#define IDS_TJS_GROUP_BY_OBJECT_TYPE_                                              L"オブジェクトのタイプによる分_"
#define IDS_TJS_OBJECT_COUNTING_MESSAGE_GROUP_BY_OBJECT_TYPE_AND_HISTORY_          L"%1 _ : [%2]\n                     %3"
#define IDS_TJS_OBJECT_COUNTING_MESSAGE_TJSGROUP_BY_OBJECT_TYPE_                   L"%1 _ : [%2]"
#define IDS_TJS_WARN_RUNNING_CODE_ON_DELETING_OBJECT_                              L"%4: 削除中のオブジェクト %1[%2] 上でコ_ドが_行されています。このオブジェクトの作成_の呼び出し履_は以下の通りです:\n                     %3"
#define IDS_TJS_WRITE_ERROR_                                                       L"_き_みエラ_が_生しました"
#define IDS_TJS_READ_ERROR_                                                        L"_み_みエラ_が_生しました。ファイルが破_している可能性や、デバイスからの_み_みに失_した可能性があります"
#define IDS_TJS_SEEK_ERROR_                                                        L"シ_クエラ_が_生しました。ファイルが破_している可能性や、デバイスからの_み_みに失_した可能性があります"
#define IDS_TJS_BYTE_CODE_BROKEN_                                                  L"バイトコ_ドファイル_み_みエラ_。ファイルが_れているかバイトコ_ドとは_なるファイルです"
#define IDS_TJS_OBJECT_HASH_MAP_LOG_VERSION_MISMATCH_                              L"Object Hash Map ログのバ_ジョンが一致しません"
#define IDS_TJS_CURRUPTED_OBJECT_HASH_MAP_LOG_                                     L"不正な Object Hash Map ログ"
#define IDS_TJS_UNKNOWN_FAILURE_                                                   L"未知のエラ_ %08X"
#define IDS_TJS_UNKNOWN_PACK_UNPACK_TEMPLATE_CHARCTER_                             L"不明な pack/unpack TEMPLATE 文字です"
#define IDS_TJS_UNKNOWN_BIT_STRING_CHARACTER_                                      L"不明な bit string 文字です"
#define IDS_TJS_UNKNOWN_HEX_STRING_CHARACTER_                                      L"不明な16_数文字です"
#define IDS_TJS_NOT_SUPPORTED_UUENCODE_                                            L"uuencode はサポ_トしていません"
#define IDS_TJS_NOT_SUPPORTED_BER_                                                 L"BER__はサポ_トしていません"
#define IDS_TJS_NOT_SUPPORTED_UNPACK_LP_                                           L"\'p\' unpack はサポ_トしていません"
#define IDS_TJS_NOT_SUPPORTED_UNPACK_P                                             L"\'P\' unpack はサポ_トしていません"
#define IDS_TVP_VERSION_INFORMATION_                                               L"吉里吉里[きりきり] Z _行コア/%1 (Compiled on %DATE% %TIME%) TJS2/%2 Copyright (C) 1997-2013 W.Dee and contributors All rights reserved."
#define IDS_TVP_VERSION_INFORMATION2_                                              L"バ_ジョン情_の__は -about を付けて起_すると__できます"
#define IDS_TVP_DOWNLOAD_PAGE_URL_                                                 L"http://krkrz.github.io/"
#define IDS_TVP_INTERNAL_ERROR_                                                    L"内部エラ_が_生しました: at %1 line %2"
#define IDS_TVP_INVALID_PARAM_                                                     L"不正なパラメ_タです"
#define IDS_TVP_WARN_DEBUG_OPTION_ENABLED_                                         L"-debug オプションが指定されているため,_在 吉里吉里はデバッグモ_ドで_作しています。デバッグモ_ドでは十分な_行速度が出ない_合があるので注意してください"
#define IDS_TVP_COMMAND_LINE_PARAM_IGNORED_AND_DEFAULT_USED_                       L"コマンドラインパラメ_タ %1 に指定された_ %2 は__のためデフォルトの_定を用います"
#define IDS_TVP_INVALID_COMMAND_LINE_PARAM_                                        L"コマンドラインパラメ_タ %1 に指定された_ %2 は__です"
#define IDS_TVP_NOT_IMPLEMENTED_                                                   L"未_装の_能を呼び出そうとしました"
#define IDS_TVP_CANNOT_OPEN_STORAGE_                                               L"ストレ_ジ %1 を_くことができません"
#define IDS_TVP_CANNOT_FIND_STORAGE_                                               L"ストレ_ジ %1 が_つかりません"
#define IDS_TVP_CANNOT_OPEN_STORAGE_FOR_WRITE_                                     L"ストレ_ジ %1 を_き_み用に_くことができません。ファイルが_き_み禁止になっていないか、あるいはファイルに_き_み_限があるかどうか、あるいはそもそもそれが_き_み可能なメディアやファイルなのかを__してください"
#define IDS_TVP_STORAGE_IN_ARCHIVE_NOT_FOUND_                                      L"ストレ_ジ %1 がア_カイブ %2 の中に_つかりません"
#define IDS_TVP_INVALID_PATH_NAME_                                                 L"パス名 %1 は__な形式です。形式が正しいかどうかを__してください"
#define IDS_TVP_UNSUPPORTED_MEDIA_NAME_                                            L"\"\"\"%1\"\" は__していないメディアタイプです\""
#define IDS_TVP_CANNOT_UNBIND_XP3EXE_                                              L"%1 は_行可能ファイルに_えますが、これに_合されたア_カイブを__できませんでした"
#define IDS_TVP_CANNOT_FIND_XP3MARK_                                               L"%1 は XP3 ア_カイブではないか、__できない形式です。ア_カイブファイルを指定すべき_面で通常のファイルを指定した_合、あるいは__できないア_カイブファイルを指定した_合などにこのエラ_が_生しますので、__してください"
#define IDS_TVP_MISSING_PATH_DELIMITER_AT_LAST_                                    L"パス名の最後には \'>\' または \'/\' を指定してください (吉里吉里２ 2.19 beta 14 よりア_カイブの区切り_号が \'#\' から \'>\' に_わりました)"
#define IDS_TVP_FILENAME_CONTAINS_SHARP_WARN_                                      L"\"(注意) \'#\' がファイル名 \"\"%1\"\" に含まれています。ア_カイブの区切り文字は吉里吉里２ 2.19 beta 14 より\'#\' から \'>\' に_わりました。もしア_カイブの区切り文字のつもりで \'#\' を使用した_合は、お手数ですが \'>\' に_えてください\""
#define IDS_TVP_CANNOT_GET_LOCAL_NAME_                                             L"ストレ_ジ名 %1 をロ_カルファイル名に__できません。ア_カイブファイル内のファイルや、ロ_カルファイルでないファイルはロ_カルファイル名に__できません。"
#define IDS_TVP_READ_ERROR_                                                        L"_み_みエラ_です。ファイルが破_している可能性や、デバイスからの_み_みに失_した可能性があります"
#define IDS_TVP_WRITE_ERROR_                                                       L"_き_みエラ_です"
#define IDS_TVP_SEEK_ERROR_                                                        L"シ_クに失_しました。ファイルが破_している可能性や、デバイスからの_み_みに失_した可能性があります"
#define IDS_TVP_TRUNCATE_ERROR_                                                    L"ファイルの_さを切り_めるのに失_しました"
#define IDS_TVP_INSUFFICIENT_MEMORY_                                               L"メモリ_保に失_しました。"
#define IDS_TVP_UNCOMPRESSION_FAILED_                                              L"ファイルの展_に失_しました。未__の__形式が指定されたか、あるいはファイルが破_している可能性があります"
#define IDS_TVP_COMPRESSION_FAILED_                                                L"ファイルの__に失_しました"
#define IDS_TVP_CANNOT_WRITE_TO_ARCHIVE_                                           L"ア_カイブにデ_タを_き_むことはできません"
#define IDS_TVP_UNSUPPORTED_CIPHER_MODE_                                           L"%1 は未__の暗号化形式か、デ_タが破_しています"
#define IDS_TVP_UNSUPPORTED_ENCODING_                                              L"%1 は未__のエンコ_ド方式です。"
#define IDS_TVP_UNSUPPORTED_MODE_STRING_                                           L"__できないモ_ド文字列の指定です(%1)"
#define IDS_TVP_UNKNOWN_GRAPHIC_FORMAT_                                            L"%1 は未知の画像形式です"
#define IDS_TVP_CANNOT_SUGGEST_GRAPHIC_EXTENSION_                                  L"%1 について_切な__子を持ったファイルを_つけられませんでした"
#define IDS_TVP_MASK_SIZE_MISMATCH_                                                L"マスク画像のサイズがメイン画像のサイズと_います"
#define IDS_TVP_PROVINCE_SIZE_MISMATCH_                                            L"_域画像 %1 はメイン画像とサイズが_います"
#define IDS_TVP_IMAGE_LOAD_ERROR_                                                  L"画像_み_み中にエラ_が_生しました/%1"
#define IDS_TVP_JPEGLOAD_ERROR_                                                    L"JPEG _み_み中にエラ_が_生しました/%1"
#define IDS_TVP_PNGLOAD_ERROR_                                                     L"PNG _み_み中にエラ_が_生しました/%1"
#define IDS_TVP_ERILOAD_ERROR_                                                     L"ERI _み_み中にエラ_が_生しました/%1"
#define IDS_TVP_TLGLOAD_ERROR_                                                     L"TLG _み_み中にエラ_が_生しました/%1"
#define IDS_TVP_INVALID_IMAGE_SAVE_TYPE_                                           L"__な保存画像形式です(%1)"
#define IDS_TVP_INVALID_OPERATION_FOR8BPP_                                         L"8bpp 画像に_しては行えない操作を行おうとしました"
#define IDS_TVP_INVALID_OPERATION_FOR32BPP_                                        L"32bpp 画像に_しては行えない操作を行おうとしました"
#define IDS_TVP_SPECIFY_WINDOW_                                                    L"Window クラスのオブジェクトを指定してください"
#define IDS_TVP_SPECIFY_LAYER_                                                     L"Layer クラスのオブジェクトを指定してください"
#define IDS_TVP_SPECIFY_LAYER_OR_BITMAP_                                           L"Layer クラスか Bitmap クラスのオブジェクトを指定してください"
#define IDS_TVP_CANNOT_ACCEPT_MODE_AUTO_                                           L"この操作で mode に omAuto を指定することは出来ません"
#define IDS_TVP_CANNOT_CREATE_EMPTY_LAYER_IMAGE_                                   L"画像サイズの横幅あるいは_幅を 0 以下の数に_定することはできません"
#define IDS_TVP_CANNOT_SET_PRIMARY_INVISIBLE_                                      L"プライマリレイヤは不可_にできません"
#define IDS_TVP_CANNOT_MOVE_PRIMARY_                                               L"プライマリレイヤは移_できません"
#define IDS_TVP_CANNOT_SET_PARENT_SELF_                                            L"自分自身を_とすることはできません"
#define IDS_TVP_CANNOT_MOVE_NEXT_TO_SELF_OR_NOT_SIBLINGS_                          L"自分自身の前後や_の_なるレイヤの前後に移_することはできません"
#define IDS_TVP_CANNOT_MOVE_PRIMARY_OR_SIBLINGLESS_                                L"プライマリレイヤや兄弟の_いレイヤは前後に移_することはできません"
#define IDS_TVP_CANNOT_MOVE_TO_UNDER_OTHER_PRIMARY_LAYER_                          L"_のプライマリレイヤ下にレイヤを移_することはできません"
#define IDS_TVP_INVALID_IMAGE_POSITION_                                            L"レイヤ_域に画像の_い_域が_生しました"
#define IDS_TVP_CANNOT_SET_MODE_TO_DISABLED_OR_MODAL_                              L"すでにモ_ダルなレイヤの_レイヤ、あるいは不可_/__なレイヤをモ_ダルにすることはできません"
#define IDS_TVP_NOT_DRAWABLE_LAYER_TYPE_                                           L"この type のレイヤでは描画や画像_み_みや画像サイズ/位置の_更/取得はできません"
#define IDS_TVP_SOURCE_LAYER_HAS_NO_IMAGE_                                         L"_送元レイヤは画像を持っていません"
#define IDS_TVP_UNSUPPORTED_LAYER_TYPE_                                            L"%1 はこの type のレイヤでは使用できません"
#define IDS_TVP_NOT_DRAWABLE_FACE_TYPE_                                            L"%1 ではこの face に描画できません"
#define IDS_TVP_CANNOT_CONVERT_LAYER_TYPE_USING_GIVEN_DIRECTION_                   L"指定されたレイヤタイプ__はできません"
#define IDS_TVP_NEGATIVE_OPACITY_NOT_SUPPORTED_ON_THIS_FACE_                       L"_の不透明度はこの face では指定できません"
#define IDS_TVP_SRC_RECT_OUT_OF_BITMAP_                                            L"_送元がビットマップ外の_域を含んでいます。正しい__に_まるように_送元を指定してください"
#define IDS_TVP_BOX_BLUR_AREA_MUST_CONTAIN_CENTER_PIXEL_                           L"矩形ブラ_の__は必ず(0,0)をその中に含む必要があります。leftとrightが_方とも正の数_、あるいは_方とも_の数_という指定はできません(topとbottomに_しても同_)"
#define IDS_TVP_BOX_BLUR_AREA_MUST_BE_SMALLER_THAN16MILLION_                       L"矩形ブラ_の__が大きすぎます。矩形ブラ_の__は1677万以下である必要があります"
#define IDS_TVP_CANNOT_CHANGE_FOCUS_IN_PROCESSING_FOCUS_                           L"フォ_カス_更_理中はフォ_カスを新たに_更することはできません"
#define IDS_TVP_WINDOW_HAS_NO_LAYER_                                               L"ウィンドウにレイヤがありません"
#define IDS_TVP_WINDOW_HAS_ALREADY_PRIMARY_LAYER_                                  L"ウィンドウにはすでにプライマリレイヤがあります"
#define IDS_TVP_SPECIFIED_EVENT_NEEDS_PARAMETER_                                   L"イベント %1 にはパラメ_タが必要です"
#define IDS_TVP_SPECIFIED_EVENT_NEEDS_PARAMETER2_                                  L"イベント %1 にはパラメ_タ %2 が必要です"
#define IDS_TVP_SPECIFIED_EVENT_NAME_IS_UNKNOWN_                                   L"イベント名 %1 は未知のイベント名です"
#define IDS_TVP_OUT_OF_RECTANGLE_                                                  L"矩形外を指定されました"
#define IDS_TVP_INVALID_METHOD_IN_UPDATING_                                        L"画面更新中はこの_能を_行できません"
#define IDS_TVP_CANNOT_CREATE_INSTANCE_                                            L"このクラスはインスタンスを作成できません"
#define IDS_TVP_UNKNOWN_WAVE_FORMAT_                                               L"%1 は__できない Wave 形式です"
#define IDS_TVP_CURRENT_TRANSITION_MUST_BE_STOPPING_                               L"_在のトランジションを停止させてから新しいトランジションを_始してください。同じレイヤに_して_数のトランジションを同_に_行しようとするとこのエラ_が_生します"
#define IDS_TVP_TRANS_HANDLER_ERROR_                                               L"トランジションハンドラでエラ_が_生しました : %1"
#define IDS_TVP_TRANS_ALREADY_REGISTERED_                                          L"トランジション %1 は既に登_されています"
#define IDS_TVP_CANNOT_FIND_TRANS_HANDER_                                          L"トランジションハンドラ %1 が_つかりません"
#define IDS_TVP_SPECIFY_TRANSITION_SOURCE_                                         L"トランジション元を指定してください"
#define IDS_TVP_LAYER_CANNOT_HAVE_IMAGE_                                           L"このレイヤは画像を持つことはできません"
#define IDS_TVP_TRANSITION_SOURCE_AND_DESTINATION_MUST_HAVE_IMAGE_                 L"トランジション元とトランジション先はともに画像を持っている必要があります"
#define IDS_TVP_CANNOT_LOAD_RULE_GRAPHIC_                                          L"ル_ル画像 %1 を_み_むことができません"
#define IDS_TVP_SPECIFY_OPTION_                                                    L"オプション %1 を指定してください"
#define IDS_TVP_TRANSITION_LAYER_SIZE_MISMATCH_                                    L"トランジション元(%1)とトランジション先(%2)のレイヤのサイズが一致しません"
#define IDS_TVP_TRANSITION_MUTUAL_SOURCE_                                          L"トランジション元のトランジション元が自分自身です"
#define IDS_TVP_HOLD_DESTINATION_ALPHA_PARAMETER_IS_NOW_DEPRECATED_                L"警告 : メソッド %1 の %2 番目に渡された hda パラメ_タは、吉里吉里２ 2.23 beta 2 より__されるようになりました。代わりに Layer.holdAlpha プロパティを用いてください。"
#define IDS_TVP_CANNOT_CONNECT_MULTIPLE_WAVE_SOUND_BUFFER_AT_ONCE_                 L"_数の WaveSoundBuffer を一つのフィルタで同_に使用することはできません"
#define IDS_TVP_INVALID_WINDOW_SIZE_MUST_BE_IN64TO32768_                           L"window は 64_32768 の__の 2 の累_で_ければなりません"
#define IDS_TVP_INVALID_OVERLAP_COUNT_MUST_BE_IN2TO32_                             L"overlap は 2_32 の__の 2 の累_で_ければなりません"
#define IDS_TVP_CURRENTLY_ASYNC_LOAD_BITMAP_                                       L"Bitmap を非同期__み中のため、このメソッドは呼び出せません"
#define IDS_TVP_FAILD_CLIPBOARD_COPY_                                              L"クリップボ_ドへのコピ_に失_しました"
#define IDS_TVP_INVALID_UTF16TO_UTF8_                                              L"UTF-16では_生し得ないUTF-8への__です"
#define IDS_TVP_INFO_LOADING_STARTUP_SCRIPT_                                       L"(info) 起_スクリプト__み中 : "
#define IDS_TVP_INFO_STARTUP_SCRIPT_ENDED_                                         L"(info) 起_スクリプト_行_了。"
#define IDS_TVP_TJS_CHAR_MUST_BE_TWO_OR_FOUR_                                      L"sizeof(tjs_char) は 2 か 4 でなければなりません。"
#define IDS_TVP_MEDIA_NAME_HAD_ALREADY_BEEN_REGISTERED_                            L"\"メディア名 \"\"%1\"\" は既に登_されています\""
#define IDS_TVP_MEDIA_NAME_IS_NOT_REGISTERED_                                      L"\"メディア名 \"\"%1\"\" は登_されていません\""
#define IDS_TVP_INFO_REBUILDING_AUTO_PATH_                                         L"(info) 自__索パステ_ブルを再__しています ..."
#define IDS_TVP_INFO_TOTAL_FILE_FOUND_AND_ACTIVATED_                               L"(info) Total %1 file(s) found, %2 file(s) activated. (%3ms)"
#define IDS_TVP_ERROR_IN_RETRIEVING_SYSTEM_ON_ACTIVATE_ON_DEACTIVATE_              L"Error in retrieving System.onActivate/onDeactivate : %1"
#define IDS_TVP_THE_HOST_IS_NOT_A16BIT_UNICODE_SYSTEM_                             L"The host is not a 16-bit unicode system."
#define IDS_TVP_INFO_TRYING_TO_READ_XP3VIRTUAL_FILE_SYSTEM_INFORMATION_FROM_       L"(info) Trying to read XP3 virtual file system information from : %1"
#define IDS_TVP_SPECIFIED_STORAGE_HAD_BEEN_PROTECTED_                              L"Specified storage had been protected!"
#define IDS_TVP_INFO_FAILED_                                                       L"(info) 失_。"
#define IDS_TVP_INFO_DONE_WITH_CONTAINS_                                           L"(info) Done. (contains %1 file(s), %2 segment(s))"
#define IDS_TVP_SEPARATOR_CRLF_                                                    L"\r\n\r\n\r\n==============================================================================\r\n==============================================================================\r\n"
#define IDS_TVP_SEPARATOR_CR_                                                      L"\n\n\n==============================================================================\n==============================================================================\n"
#define IDS_TVP_DEFAULT_FONT_NAME_                                                 L"ＭＳ Ｐゴシック"
#define IDS_TVP_CANNOT_OPEN_FONT_FILE_                                             L"Can\'t open font file \'%1$s\'"
#define IDS_TVP_FONT_CANNOT_BE_USED_                                               L"フォント \'%1$s\' は使用できません"
#define IDS_TVP_FONT_RASTERIZE_ERROR_                                              L"フォント ラスタライズ エラ_."
#define IDS_TVP_BIT_FIELDS_NOT_SUPPORTED_                                          L"BITFIELDS not supported."
#define IDS_TVP_COMPRESSED_BMP_NOT_SUPPORTED_                                      L"Compressed BMP not supported."
#define IDS_TVP_UNSUPPORTED_COLOR_MODE_FOR_PALETT_IMAGE_                           L"Unsupported color mode for palettized image."
#define IDS_TVP_NOT_WINDOWS_BMP_                                                   L"This is not a Windows BMP file or an OS/2 BMP file."
#define IDS_TVP_UNSUPPORTED_HEADER_VERSION_                                        L"Non-supported header version."
#define IDS_TVP_INFO_TOUCHING_                                                     L"(info) Touching "
#define IDS_TVP_ABORTED_TIME_OUT_                                                  L" ... 中断 [タイムアウト]"
#define IDS_TVP_ABORTED_LIMIT_BYTE_                                                L" ... 中断 [バイトサイズ上限_超_]"
#define IDS_TVP_FAILD_GLYPH_FOR_DRAW_GLYPH_                                        L"Faild glyph for DrawGlyph."
#define IDS_TVP_LAYER_OBJECT_IS_NOT_PROPERLY_CONSTRUCTED_                          L"Panic! Layer object is not properly constructed. The constructor was not called??"
#define IDS_TVP_UNKNOWN_UPDATE_TYPE_                                               L"不明な update タイプ"
#define IDS_TVP_UNKNOWN_TRANSITION_TYPE_                                           L"不明な transition タイプ"
#define IDS_TVP_UNSUPPORTED_UPDATE_TYPE_TUT_GIVE_UPDATE_                           L"Update タイプの tutGiveUpdate はサポ_トしていません"
#define IDS_TVP_ERROR_CODE_                                                        L"エラ_コ_ド : "
#define IDS_TVP_UNSUPPORTED_JPEG_PALETTE_                                          L"JPEG はパレット画像をサポ_トしていません"
#define IDS_TVP_LIBPNG_ERROR_                                                      L"libpng エラ_."
#define IDS_TVP_UNSUPPORTED_COLOR_TYPE_PALETTE_                                    L"Unsupported color type for palattized image"
#define IDS_TVP_UNSUPPORTED_COLOR_TYPE_                                            L"サポ_トしていないカラ_タイプ"
#define IDS_TVP_TOO_LARGE_IMAGE_                                                   L"Too large image"
#define IDS_TVP_PNG_SAVE_ERROR_                                                    L"PNG save error."
#define IDS_TVP_TLG_UNSUPPORTED_UNIVERSAL_TRANSITION_RULE_                         L"TLG cannot be used as universal transition rule, province(_p) or mask(_m) images."
#define IDS_TVP_UNSUPPORTED_COLOR_COUNT_                                           L"Unsupported color count : "
#define IDS_TVP_DATA_FLAG_MUST_BE_ZERO_                                            L"Data flag must be 0 (any flags are not yet supported)"
#define IDS_TVP_UNSUPPORTED_COLOR_TYPE_COLON_                                      L"サポ_トしていないカラ_タイプです : "
#define IDS_TVP_UNSUPPORTED_EXTERNAL_GOLOMB_BIT_LENGTH_TABLE_                      L"外部 golomb ビット_テ_ブルはサポ_トしていません"
#define IDS_TVP_UNSUPPORTED_ENTROPY_CODING_METHOD_                                 L"サポ_トしていないエントロピ_コ_ドメソッドです"
#define IDS_TVP_INVALID_TLG_HEADER_OR_VERSION_                                     L"不正な TLG ヘッダ_か、サポ_トしていない TLG バ_ジョンです"
#define IDS_TVP_TLG_MALFORMED_TAG_MISSION_COLON_AFTER_NAME_LENGTH_                 L"Malformed TLG SDS tag structure, missing colon after name length"
#define IDS_TVP_TLG_MALFORMED_TAG_MISSION_EQUALS_AFTER_NAME_                       L"Malformed TLG SDS tag structure, missing equals after name"
#define IDS_TVP_TLG_MALFORMED_TAG_MISSION_COLON_AFTER_VAUE_LENGTH_                 L"Malformed TLG SDS tag structure, missing colon after value length"
#define IDS_TVP_TLG_MALFORMED_TAG_MISSION_COMMA_AFTER_TAG_                         L"Malformed TLG SDS tag structure, missing comma after a tag"
#define IDS_TVP_FILE_SIZE_IS_ZERO_                                                 L"ファイルサイズがゼロです"
#define IDS_TVP_MEMORY_ALLOCATION_ERROR_                                           L"メモリ_保に失_しました"
#define IDS_TVP_FILE_READ_ERROR_                                                   L"ファイル__みエラ_"
#define IDS_TVP_INVALID_PRERENDERED_FONT_FILE_                                     L"シグネチャが_つからないか、プリレンダ_フォントファイルではありません"
#define IDS_TVP_NOT16BIT_UNICODE_FONT_FILE_                                        L"16 ビット UNICODE フォントファイルではありません"
#define IDS_TVP_INVALID_HEADER_VERSION_                                            L"不正なバ_ジョンのヘッダ_です"
#define IDS_TVP_TLG_INSUFFICIENT_MEMORY_                                           L"SaveTLG6: メモリ不足です"
#define IDS_TVP_TLG_TOO_LARGE_BIT_LENGTH_                                          L"SaveTLG6: ビット_が_すぎます (渡された画像が大きすぎる可能性があります)"
#define IDS_TVP_CANNOT_RETRIVE_INTERFACE_FROM_DRAW_DEVICE                          L"渡された Draw Device からインタ_フェイスを取得できません"
#define IDS_TVP_SCRIPT_EXCEPTION_RAISED_                                           L"スクリプトで例外が_生しました"
#define IDS_TVP_HARDWARE_EXCEPTION_RAISED_                                         L"ハ_ドウェア例外が_生しました"
#define IDS_TVP_MAIN_CDPNAME_                                                      L"スクリプトエディタ (メイン)"
#define IDS_TVP_EXCEPTION_CDPNAME_                                                 L"スクリプトエディタ (例外通知)"
#define IDS_TVP_CANNNOT_LOCATE_UIDLLFOR_FOLDER_SELECTION_                          L"フォルダ/ア_カイブの__画面を表示しようとしましたが krdevui.dll が_つからないので表示できません.\n_行するフォルダ/ア_カイブはコマンドラインの引数として指定してください"
#define IDS_TVP_INVALID_UIDLL_                                                     L"krdevui.dll が_常か、バ_ジョンが一致しません"
#define IDS_TVP_INVALID_BPP_                                                       L"__な色深度です"
#define IDS_TVP_CANNOT_LOAD_PLUGIN_                                                L"プラグイン %1 を_み_めません"
#define IDS_TVP_NOT_VALID_PLUGIN_                                                  L"%1 は有_なプラグインではありません"
#define IDS_TVP_PLUGIN_UNINIT_FAILED_                                              L"プラグインの解放に失_しました"
#define IDS_TVP_CANNNOT_LINK_PLUGIN_WHILE_PLUGIN_LINKING_                          L"プラグインの接_中に他のプラグインを接_することはできまません"
#define IDS_TVP_NOT_SUSIE_PLUGIN_                                                  L"_常な Susie プラグインです"
#define IDS_TVP_SUSIE_PLUGIN_ERROR_                                                L"Susie プラグインでエラ_が_生しました/エラ_コ_ド %1"
#define IDS_TVP_CANNOT_RELEASE_PLUGIN_                                             L"指定されたプラグインは使用中のため解放できません"
#define IDS_TVP_NOT_LOADED_PLUGIN_                                                 L"%1 は_み_まれていません"
#define IDS_TVP_CANNOT_ALLOCATE_BITMAP_BITS_                                       L"ビットマップ用メモリを_保できません/%1(size=%2)"
#define IDS_TVP_SCAN_LINE_RANGE_OVER_                                              L"スキャンライン %1 は__(0_%2)を超えています"
#define IDS_TVP_PLUGIN_ERROR_                                                      L"プラグインでエラ_が_生しました/%1"
#define IDS_TVP_INVALID_CDDADRIVE_                                                 L"指定されたドライブでは CD-DA を再生できません"
#define IDS_TVP_CDDADRIVE_NOT_FOUND_                                               L"CD-DA を再生できるドライブが_つかりません"
#define IDS_TVP_MCIERROR_                                                          L"MCI でエラ_が_生しました : %1"
#define IDS_TVP_INVALID_SMF_                                                       L"有_な SMF ファイルではありません : %1"
#define IDS_TVP_MALFORMED_MIDIMESSAGE_                                             L"指定されたメッセ_ジは MIDI メッセ_ジとして有_な形式ではありません"
#define IDS_TVP_CANNOT_INIT_DIRECT_SOUND_                                          L"DirectSound を初期化できません : %1"
#define IDS_TVP_CANNOT_CREATE_DSSECONDARY_BUFFER_                                  L"DirectSound セカンダリバッファを作成できません : %1/%2"
#define IDS_TVP_INVALID_LOOP_INFORMATION_                                          L"ル_プ情_ %1 は_常です"
#define IDS_TVP_NOT_CHILD_MENU_ITEM_                                               L"指定されたメニュ__目はこのメニュ__目の子ではありません"
#define IDS_TVP_CANNOT_INIT_DIRECT3D_                                              L"Direct3D を初期化できません : %1"
#define IDS_TVP_CANNOT_FIND_DISPLAY_MODE_                                          L"_合する画面モ_ドが_つかりません : %1"
#define IDS_TVP_CANNOT_SWITCH_TO_FULL_SCREEN_                                      L"フルスクリ_ンに切り替えられません : %1"
#define IDS_TVP_INVALID_PROPERTY_IN_FULL_SCREEN_                                   L"フルスクリ_ン中では操作できないプロパティを_定しようとしました"
#define IDS_TVP_INVALID_METHOD_IN_FULL_SCREEN_                                     L"フルスクリ_ン中では操作できないメソッドを呼び出そうとしました"
#define IDS_TVP_CANNOT_LOAD_CURSOR_                                                L"マウスカ_ソル %1 の_み_みに失_しました"
#define IDS_TVP_CANNOT_LOAD_KR_MOVIE_DLL_                                          L"ビデオ/Shockwave Flash を再生するためには krmovie.dll / krflash.dll が必要ですが _み_むことができません"
#define IDS_TVP_INVALID_KR_MOVIE_DLL_                                              L"krmovie.dll/krflash.dll が_常か __できないバ_ジョンです"
#define IDS_TVP_ERROR_IN_KR_MOVIE_DLL_                                             L"krmovie.dll/krflash.dll 内でエラ_が_生しました/%1"
#define IDS_TVP_WINDOW_ALREADY_MISSING_                                            L"ウィンドウはすでに存在していません"
#define IDS_TVP_PRERENDERED_FONT_MAPPING_FAILED_                                   L"レンダリング_みフォントのマッピングに失_しました : %1"
#define IDS_TVP_CONFIG_FAIL_ORIGINAL_FILE_CANNOT_BE_REWRITTEN_                     L"%1 に_き_みできません。ソフトウェアが_行中のままになっていないか、あるいは_き_み_限があるかどうかを__してください"
#define IDS_TVP_CONFIG_FAIL_TEMP_EXE_NOT_ERASED_                                   L"%1 の_了を__できないため、これを削除できませんでした(このファイルは削除して__です)"
#define IDS_TVP_EXECUTION_FAIL_                                                    L"%1 を_行できません"
#define IDS_TVP_PLUGIN_UNBOUND_FUNCTION_ERROR_                                     L"プラグインから_数 %1 を要求されましたが、その_数は本体内に存在しません。プラグインと本体のバ_ジョンが正しく__しているか__してください"
#define IDS_TVP_EXCEPTION_HAD_BEEN_OCCURED_                                        L" = (例外_生)"
#define IDS_TVP_CONSOLE_RESULT_                                                    L"コンソ_ル : "
#define IDS_TVP_INFO_LISTING_FILES_                                                L"(info) Listing files in %1 …"
#define IDS_TVP_INFO_TOTAL_PHYSICAL_MEMORY_                                        L"(info) Total physical memory : %1"
#define IDS_TVP_INFO_SELECTED_PROJECT_DIRECTORY_                                   L"(info) Selected project directory : %1"
#define IDS_TVP_TOO_SMALL_EXECUTABLE_SIZE_                                         L"too small executable size."
#define IDS_TVP_INFO_LOADING_EXECUTABLE_EMBEDDED_OPTIONS_FAILED_                   L"(info) Loading executable embedded options failed (ignoring) : %1"
#define IDS_TVP_INFO_LOADING_EXECUTABLE_EMBEDDED_OPTIONS_SUCCEEDED_                L"(info) Loading executable embedded options succeeded."
#define IDS_TVP_FILE_NOT_FOUND_                                                    L"file not found."
#define IDS_TVP_INFO_LOADING_CONFIGURATION_FILE_FAILED_                            L"\"(info) Loading configuration file \"\"%1\"\" failed (ignoring) : %2\""
#define IDS_TVP_INFO_LOADING_CONFIGURATION_FILE_SUCCEEDED_                         L"\"(info) Loading configuration file \"\"%1\"\" succeeded.\""
#define IDS_TVP_INFO_DATA_PATH_DOES_NOT_EXIST_TRYING_TO_MAKE_IT_                   L"(info) Data path does not exist, trying to make it ... %1"
#define IDS_TVP_OK_                                                                L"成功。"
#define IDS_TVP_FAILD_                                                             L"失_。"
#define IDS_TVP_INFO_DATA_PATH_                                                    L"(info) Data path : %1"
#define IDS_TVP_INFO_SPECIFIED_OPTION_EARLIER_ITEM_HAS_MORE_PRIORITY_              L"(info) Specified option(s) (earlier item has more priority) :"
#define IDS_TVP_NONE_                                                              L" (none)"
#define IDS_TVP_INFO_CPU_CLOCK_ROUGHLY_                                            L"(info) CPU clock (roughly) : %dMHz"
#define IDS_TVP_PROGRAM_STARTED_ON_                                                L"%1 (%2) 上で_行が_始されました"
#define IDS_TVP_KIRIKIRI_                                                          L"吉里吉里"
#define IDS_TVP_UNKNOWN_ERROR_                                                     L"不明なエラ_が_生しました。"
#define IDS_TVP_EXIT_CODE_                                                         L"_了コ_ド: %d\n"
#define IDS_TVP_FATAL_ERROR_                                                       L"致命的なエラ_が_生しました"
#define IDS_TVP_ENABLE_DIGITIZER_                                                  L"有_なデジタイザ_"
#define IDS_TVP_TOUCH_INTEGRATED_TOUCH_                                            L"_合型のタッチ デジタイザ_が入力に使用されています。"
#define IDS_TVP_TOUCH_EXTERNAL_TOUCH_                                              L"外付けのタッチ デジタイザ_が入力に使用されています。"
#define IDS_TVP_TOUCH_INTEGRATED_PEN_                                              L"_合型のペン デジタイザ_が入力に使用されています。"
#define IDS_TVP_TOUCH_EXTERNAL_PEN_                                                L"外付けのペン デジタイザ_が入力に使用されています。"
#define IDS_TVP_TOUCH_MULTI_INPUT_                                                 L"_数入力がサポ_トされた入力デジタイザ_が入力に使用されています。"
#define IDS_TVP_TOUCH_READY_                                                       L"入力デジタイザ_で入力の__ができています。"
#define IDS_TVP_CPU_CHECK_FAILURE_                                                 L"CPUのチェック失_"
#define IDS_TVP_CPU_CHECK_FAILURE_CPU_FAMILY_OR_LESSER_IS_NOT_SUPPORTED_           L"CPU check failure: CPU family 4 or lesser is not supported\r\n%1"
#define IDS_TVP_INFO_CPU_NUMBER_                                                   L"(info) CPU #%1 : "
#define IDS_TVP_CPU_CHECK_FAILURE_NOT_SUPPRTED_CPU_                                L"CPUチェック失_: サポ_トしていないCPU\r\n%1"
#define IDS_TVP_INFO_FINALLY_DETECTED_CPU_FEATURES_                                L"(info) finally detected CPU features : %1"
#define IDS_TVP_CPU_CHECK_FAILURE_NOT_SUPPORTED_CPU_                               L"CPU check failure: Not supported CPU\r\n%1"
#define IDS_TVP_INFO_CPU_CLOCK_                                                    L"(info) CPU clock : %.1fMHz"
#define IDS_TVP_LAYER_BITMAP_BUFFER_UNDERRUN_DETECTED_CHECK_YOUR_DRAWING_CODE_     L"Layer bitmap: Buffer underrun detected. Check your drawing code!"
#define IDS_TVP_LAYER_BITMAP_BUFFER_OVERRUN_DETECTED_CHECK_YOUR_DRAWING_CODE_      L"Layer bitmap: Buffer overrun detected. Check your drawing code!"
#define IDS_TVP_FAILD_TO_CREATE_DIRECT3D_                                          L"Direct3D9 生成失_"
#define IDS_TVP_FAILD_TO_DECIDE_BACKBUFFER_FORMAT_                                 L"Faild to decide backbuffer format."
#define IDS_TVP_FAILD_TO_CREATE_DIRECT3DDEVICE_                                    L"Faild to create Direct3D9 Device."
#define IDS_TVP_FAILD_TO_SET_VIEWPORT_                                             L"Faild to set viewport."
#define IDS_TVP_FAILD_TO_SET_RENDER_STATE_                                         L"Faild to set render state."
#define IDS_TVP_WARNING_IMAGE_SIZE_TOO_LARGE_MAY_BE_CANNOT_CREATE_TEXTURE_         L"warning : Image size too large. May be cannot create texture."
#define IDS_TVP_USE_POWER_OF_TWO_SURFACE_                                          L"2の累_サイズのサ_フェイスを使用します。"
#define IDS_TVP_CANNOT_ALLOCATE_D3DOFF_SCREEN_SURFACE_                             L"Cannot allocate D3D off-screen surface/HR=%1"
#define IDS_TVP_BASIC_DRAW_DEVICE_FAILED_TO_CREATE_DIRECT3DDEVICES_                L"BasicDrawDevice: Failed to create Direct3D devices: %1"
#define IDS_TVP_BASIC_DRAW_DEVICE_FAILED_TO_CREATE_DIRECT3DDEVICES_UNKNOWN_REASON_ L"BasicDrawDevice: Failed to create Direct3D devices: unknown reason"
#define IDS_TVP_BASIC_DRAW_DEVICE_TEXTURE_HAS_ALREADY_BEEN_LOCKED_                 L"BasicDrawDevice: テクスチャ_は既にロックされています (EndBitmapCompletion() を呼ばずに StartBitmapCompletion() を2回呼び出しています), アンロックしてください."
#define IDS_TVP_INTERNAL_ERROR_RESULT_                                             L"Internal error/HR=%1"
#define IDS_TVP_BASIC_DRAW_DEVICE_INF_POLYGON_DRAWING_FAILED_                      L"BasicDrawDevice: (inf) ポリゴン描画に失_しました/HR=%1"
#define IDS_TVP_BASIC_DRAW_DEVICE_INF_DIRECT3DDEVICE_PRESENT_FAILED_               L"BasicDrawDevice: (inf) IDirect3DDevice::Present failed/HR=%1"
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_RESTART_                L"ChangeDisplaySettings failed: DISP_CHANGE_RESTART"
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_BAD_FLAGS_              L"ChangeDisplaySettings failed: DISP_CHANGE_BADFLAGS"
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_BAD_PARAM_              L"ChangeDisplaySettings failed: DISP_CHANGE_BADPARAM"
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_FAILED_                 L"ChangeDisplaySettings failed: DISP_CHANGE_FAILED"
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_BAD_MODE_               L"ChangeDisplaySettings failed: DISP_CHANGE_BADMODE"
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_NOT_UPDATED_            L"ChangeDisplaySettings failed: DISP_CHANGE_NOTUPDATED"
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_UNKNOWN_REASON_                     L"ChangeDisplaySettings 失_: 不明な理由 (%1)"
#define IDS_TVP_FAILED_TO_CREATE_SCREEN_DC_                                        L"スクリ_ンデバイスコンテキストの取得に失_しました"
#define IDS_TVP_FAILED_TO_CREATE_OFFSCREEN_BITMAP_                                 L"オフスクリ_ンビットマップの生成に失_しました"
#define IDS_TVP_FAILED_TO_CREATE_OFFSCREEN_DC_                                     L"オフスクリ_ンデバイスコンテキストの生成に失_しました"
#define IDS_TVP_INFO_SUSIE_PLUGIN_INFO_                                            L"(info) Susie プラグイン情_ : %1"
#define IDS_TVP_SUSIE_PLUGIN_UNSUPPORTED_BITMAP_HEADER_                            L"サポ_トしていない Bitmap ヘッダ_が Susie プラグインから渡されました"
#define IDS_TVP_BASIC_DRAW_DEVICE_FAILED_TO_CREATE_DIRECT3DDEVICE_                 L"BasicDrawDevice: Direct3D Device の生成に失_しました : %1"
#define IDS_TVP_BASIC_DRAW_DEVICE_FAILED_TO_CREATE_DIRECT3DDEVICE_UNKNOWN_REASON_  L"BasicDrawDevice: Direct3D Device の生成に失_しました : 不明な理由"
#define IDS_TVP_COULD_NOT_CREATE_ANY_DRAW_DEVICE_                                  L"Fatal: どの drawer オブジェクトも生成できませんでした"
#define IDS_TVP_BASIC_DRAW_DEVICE_DOES_NOT_SUPPORTE_LAYER_MANAGER_MORE_THAN_ONE_   L"\"\"\"Basic Draw\"\" デバイスでは２つ以上のLayer Managerを登_できない\""
#define IDS_TVP_INVALID_VIDEO_SIZE_                                                L"__なビデオサイズ"
#define IDS_TVP_ROUGH_VSYNC_INTERVAL_READ_FROM_API_                                L"API から取得したリフレッシュレ_ト : "
#define IDS_TVP_ROUGH_VSYNC_INTERVAL_STILL_SEEMS_WRONG_                            L"リフレッシュレ_トはまだ__っているようなので、デフォルト_(16)と_定します"
#define IDS_TVP_INFO_FOUND_DIRECT3DINTERFACE_                                      L"(info) IDirect3D9 以上のインタ_フェイスが_つかりました。_在の Direct3D ドライバ情_を取得します..."
#define IDS_TVP_INFO_FAILD_                                                        L"(info) 失_"
#define IDS_TVP_INFO_DIRECT3D_                                                     L"(info) Direct3D __み..."
#define IDS_TVP_CANNOT_LOAD_D3DDLL_                                                L"d3d9.dll をロ_ドできません"
#define IDS_TVP_NOT_FOUND_DIRECT3DCREATE_                                          L"Direct3DCreate9 が d3d9.dll に_つかりません"
#define IDS_TVP_INFO_ENVIRONMENT_USING_                                            L"(info) environment: %1 を使用"
#define IDS_TVP_INFO_SEARCH_BEST_FULLSCREEN_RESOLUTION_                            L"(info) 最_なフルスクリ_ン解像度を_索 ..."
#define IDS_TVP_INFO_CONDITION_PREFERRED_SCREEN_MODE_                              L"(info) condition: 推_スクリ_ンモ_ド: %1"
#define IDS_TVP_INFO_CONDITION_MODE_                                               L"(info) condition: モ_ド: %1"
#define IDS_TVP_INFO_CONDITION_ZOOM_MODE_                                          L"(info) condition: ズ_ムモ_ド: %1"
#define IDS_TVP_INFO_ENVIRONMENT_DEFAULT_SCREEN_MODE_                              L"(info) environment: デフォルトスクリ_ンモ_ド: %1"
#define IDS_TVP_INFO_ENVIRONMENT_DEFAULT_SCREEN_ASPECT_RATIO_                      L"(info) environment: デフォルトスクリ_ンアスペクトレ_ト: %1 : %2"
#define IDS_TVP_INFO_ENVIRONMENT_AVAILABLE_DISPLAY_MODES_                          L"(info) environment: 有_なディスプレイモ_ド:"
#define IDS_TVP_INFO_NOT_FOUND_SCREEN_MODE_FROM_DRIVER_                            L"(info) Panic! ドライバ_から提供されたスクリ_ンモ_ドに_切なものはありません。デフォルト画面サイズ、色数を_します"
#define IDS_TVP_INFO_RESULT_CANDIDATES_                                            L"(info) result: candidates:"
#define IDS_TVP_INFO_TRY_SCREEN_MODE_                                              L"(info) スクリ_ンモ_ドの %1 を_みる"
#define IDS_TVP_ALL_SCREEN_MODE_ERROR_                                             L"全スクリ_ンモ_ドを_しましたが、使用可能なモ_ドはありませんでした"
#define IDS_TVP_INFO_CHANGE_SCREEN_MODE_SUCCESS_                                   L"(info) スクリ_ンモ_ド_更に成功しました"
#define IDS_TVP_SELECT_XP3FILE_OR_FOLDER_                                          L"XP3ファイルかフォルダを__してください"
#define IDS_TVP_D3D_ERR_DEVICE_LOST_                                               L"D3D : デバイスは消失しています。_在リセットできません。"
#define IDS_TVP_D3D_ERR_DRIVER_IINTERNAL_ERROR_                                    L"D3D : ドライバ内部でエラ_が_生しました。アプリケ_ションをシャットダウンする必要があります。"
#define IDS_TVP_D3D_ERR_INVALID_CALL_                                              L"D3D : メソッドの呼び出しが__です。メソッドのパラメ_タが有_なポインタではない等の可能性があります。"
#define IDS_TVP_D3D_ERR_OUT_OF_VIDEO_MEMORY_                                       L"D3D : Direct3D が_理を行うのに十分なディスプレイ メモリがありません"
#define IDS_TVP_D3D_ERR_OUT_OF_MEMORY_                                             L"D3D : Direct3D が呼び出しを完了するための十分なメモリを割り当てることができませんでした"
#define IDS_TVP_D3D_ERR_WRONG_TEXTURE_FORMAT_                                      L"D3D : テクスチャ サ_フェイスのピクセル フォ_マットが__です"
#define IDS_TVP_D3D_ERR_UNSUPORTED_COLOR_OPERATION_                                L"D3D : 色_に_して指定されているテクスチャ ブレンディング_理を、デバイスがサポ_トしていません"
#define IDS_TVP_D3D_ERR_UNSUPORTED_COLOR_ARG_                                      L"D3D : 色_に_して指定されているテクスチャ ブレンディング引数を、デバイスがサポ_トしていません"
#define IDS_TVP_D3D_ERR_UNSUPORTED_AALPHT_OPERATION_                               L"D3D : アルファ チャンネルに_して指定されているテクスチャ ブレンディング_理を、デバイスがサポ_トしていません"
#define IDS_TVP_D3D_ERR_UNSUPORTED_ALPHA_ARG_                                      L"D3D : アルファ チャンネルに_して指定されているテクスチャ ブレンディング引数を、デバイスがサポ_トしていません"
#define IDS_TVP_D3D_ERR_TOO_MANY_OPERATIONS_                                       L"D3D : デバイスがサポ_トしている数より多くのテクスチャ フィルタリング_理を、アプリケ_ションが要求しています"
#define IDS_TVP_D3D_ERR_CONFLICTIONING_TEXTURE_FILTER_                             L"D3D : _在のテクスチャ フィルタは同_には使えません"
#define IDS_TVP_D3D_ERR_UNSUPORTED_FACTOR_VALUE_                                   L"D3D : デバイスが指定されたテクスチャ_数_をサポ_トしていません"
#define IDS_TVP_D3D_ERR_CONFLICTIONING_RENDER_STATE_                               L"D3D : _在_定されているレンダリング ステ_トは同_には使えません"
#define IDS_TVP_D3D_ERR_UNSUPPORTED_TEXTURE_FILTER_                                L"D3D : デバイスが指定されたテクスチャ フィルタをサポ_トしていません"
#define IDS_TVP_D3D_ERR_CONFLICTIONING_TEXTURE_PALETTE_                            L"D3D : _在のテクスチャは同_には使えません"
#define IDS_TVP_D3D_ERR_NOT_FOUND_                                                 L"D3D : 要求された_目が_つかりませんでした"
#define IDS_TVP_D3D_ERR_MORE_DATA_                                                 L"D3D : 指定されたバッファ サイズに保持できる以上のデ_タが存在します"
#define IDS_TVP_D3D_ERR_DEVICE_NOT_RESET_                                          L"D3D : デバイスは、消失していますが、_在リセットできます"
#define IDS_TVP_D3D_ERR_NOT_AVAILABLE_                                             L"D3D : このデバイスは、照会されたテクニックをサポ_トしていません"
#define IDS_TVP_D3D_ERR_INVALID_DEVICE_                                            L"D3D : 要求されたデバイスの__が__です"
#define IDS_TVP_D3D_ERR_DRIVER_INVALID_CALL_                                       L"D3D : 使用されません"
#define IDS_TVP_D3D_ERR_WAS_STILL_DRAWING_                                         L"D3D : このサ_フェスとの_で情_を_送している以前のビット演算が不完全です"
#define IDS_TVP_D3D_ERR_DEVICE_HUNG_                                               L"D3D : このコ_ドを返したデバイスが原因で、ハ_ドウェア アダプタ_が OS によってリセットされました"
#define IDS_TVP_D3D_ERR_UNSUPPORTED_OVERLAY_                                       L"D3D : 指定されたサイズまたはディスプレイ モ_ドのオ_バ_レイをデバイスがサポ_トしていません。"
#define IDS_TVP_D3D_ERR_UNSUPPORTED_OVERLAY_FORMAT_                                L"D3D : 指定されたサ_フェス フォ_マットのオ_バ_レイをデバイスがサポ_トしていません。"
#define IDS_TVP_D3D_ERR_CANNOT_PROTECT_CONTENT_                                    L"D3D : D3DERR_CANNOTPROTECTCONTENT"
#define IDS_TVP_D3D_ERR_UNSUPPORTED_CRYPTO_                                        L"D3D : 指定された暗号化アルゴリズムをサポ_トしていません。"
#define IDS_TVP_D3D_ERR_PRESENT_STATISTICS_DIS_JOINT_                              L"D3D : D3DERR_PRESENT_STATISTICS_DISJOINT"
#define IDS_TVP_D3D_ERR_DEVICE_REMOVED_                                            L"D3D : ハ_ドウェア アダプタ_が削除されています"
#define IDS_TVP_D3D_OK_NO_AUTO_GEN_                                                L"D3D : 成功しましたが、このフォ_マットに_するミップマップの自_生成はサポ_トされていません"
#define IDS_TVP_D3D_ERR_FAIL_                                                      L"D3D : Direct3D サブシステム内で原因不明のエラ_が_生しました"
#define IDS_TVP_D3D_ERR_INVALID_ARG_                                               L"D3D : __なパラメ_タが_数に渡されました"
#define IDS_TVP_D3D_UNKNOWN_ERROR_                                                 L"D3D : 不明なエラ_が_生しました"
#define IDS_TVP_EXCEPTION_ACCESS_VIOLATION_                                        L"Access Violation: スレッドが_切なアクセス_を持たない_想アドレスに_して、_み取りまたは_き_みを_みました。"
#define IDS_TVP_EXCEPTION_BREAKPOINT_                                              L"Break Point: ブレ_クポイントに到_しました。"
#define IDS_TVP_EXCEPTION_DATATYPE_MISALIGNMENT_                                   L"Data Type Misalignment: 境界整列をサポ_トしないハ_ドウェア上で、スレッドが境界に整列していないデ_タの_み取りまたは_き_みを_みました。たとえば、16 ビットの_は 2 バイトの境界_上に、32 ビットの_は 4 バイトの境界_上に整列していなければなりません。"
#define IDS_TVP_EXCEPTION_SINGLE_STEP_                                             L"Single Step: トレ_ストラップなどの_一命令メカニズムから 1 つの命令の_行が通知されました。"
#define IDS_TVP_EXCEPTION_ARRAY_BOUNDS_EXCEEDED_                                   L"Array Bounds Exceede: スレッドが__外の配列要素にアクセスしようとしました。使用中のハ_ドウェアは境界チェックをサポ_トしています。"
#define IDS_TVP_EXCEPTION_FLT_DENORMAL_OPERAND_                                    L"Denormal Operand: 浮_小数点演算のオペランドの 1 つが不正_化_です。不正_化_とは、小さすぎて__の浮_小数点_として表_できない_です。"
#define IDS_TVP_EXCEPTION_FLT_DIVIDE_BY_ZERO_                                      L"Divide By Zero: スレッドが浮_小数点_を 0 の浮_小数点除数で除算しようとしました。"
#define IDS_TVP_EXCEPTION_FLT_INEXACT_RESULT_                                      L"Inexact Result: 浮_小数点演算の_果を 10 _小数で正_に表_できません。"
#define IDS_TVP_EXCEPTION_FLT_INVALID_OPERATION_                                   L"Invalid Operation: このリストに含まれていない例外が_生しました。"
#define IDS_TVP_EXCEPTION_FLT_OVERFLOW_                                            L"Overflow: 浮_小数点演算の指数が大きく、__する型によって表_できません。"
#define IDS_TVP_EXCEPTION_FLT_STACK_CHECK_                                         L"Stack Check: 浮_小数点演算の_果、スタックのオ_バ_フロ_またはアンダ_フロ_が_生しました。"
#define IDS_TVP_EXCEPTION_FLT_UNDERFLOW_                                           L"Underflow: 浮_小数点演算の指数が小さく、__する型によって表_できません。"
#define IDS_TVP_EXCEPTION_INT_DIVIDE_BY_ZERO_                                      L"Divide By Zero: スレッドが整数_を 0 の整数除数で除算しようとしました。"
#define IDS_TVP_EXCEPTION_INT_OVERFLOW_                                            L"Overflow: 整数演算_果の最上位ビットが_り上がりました。"
#define IDS_TVP_EXCEPTION_PRIV_INSTRUCTION_                                        L"Priv Instruction: _在のマシンモ_ドで_可されていない演算を行う命令をスレッドが_行しようとしました。"
#define IDS_TVP_EXCEPTION_NONCONTINUABLE_EXCEPTION_                                L"Noncontinuable Exception: __不可能な例外が_生した後、スレッドが_行を__しようとしました。"
#define IDS_TVP_EXCEPTION_GUARD_PAGE_                                              L"Guard Page: PAGE_GUARD で保_されたメモリにアクセスしました。"
#define IDS_TVP_EXCEPTION_ILLEGAL_INSTRUCTION_                                     L"Illegal Instruction: __な命令を_行しようとしました。"
#define IDS_TVP_EXCEPTION_IN_PAGE_ERROR_                                           L"In Page Error: 存在しないペ_ジへアクセスしようとしました、またシステムはペ_ジをロ_ドできません。 "
#define IDS_TVP_EXCEPTION_INVALID_DISPOSITION_                                     L"Invalid Disposition: 例外ハンドラは__な配置をディスパッチャに返しました。C言_のような高水_言_では_生しません。"
#define IDS_TVP_EXCEPTION_INVALID_HANDLE_                                          L"Invalid Handle: __な(おそらく既に_じられている)カ_ネルオブジェクトのハンドルを使用しました。"
#define IDS_TVP_EXCEPTION_STACK_OVERFLOW_                                          L"Stack Overflow: スタックを使い果たしました。"
#define IDS_TVP_EXCEPTION_UNWIND_CCONSOLIDATE_                                     L"Unwind Consolidate: フレ_ム_合が_行されました。"
#define IDS_TVP_CANNOT_SHOW_MODAL_AREADY_SHOWED_                                   L"既に表示、もしくは__になっているウィンドウをモ_ダル表示することは出来ません。"
#define IDS_TVP_CANNOT_SHOW_MODAL_SINGLE_WINDOW                                    L"ウィンドウが1_の_モ_ダル表示することは出来ません。"
#define IDS_TVP_UNKNOW_QT_ERROR                                                    L"未知的Qt错误"
#endif
