class GameWorld extends Node
{
	var names=%[];
	var base = void;
	var layers = [];
	var messages = [];
	function GameWorld () 
	{
		super.Node(void);
	}

	function finalize () 
	{
		super.finalize();
	}

	function visit () 
	{
		Node.DrawIndex = 0;
		super.visit();
		this.onTouchUpdate();
	}

	function initialize (w,h) 
	{
		this.setSize(w,h);
	}

	function release (name) 
	{
		if (typeof names[name] != 'undefined') {
			invalidate names[name];
			delete names[name];
		}
	}
}