#-------------------------------------------------
#
# Project created by QtCreator 2015-10-08T11:26:02
#
#-------------------------------------------------

QT       += core gui opengl

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = DollEngine
TEMPLATE = app

CONFIG += c++11

DEFINES += __QT__

INCLUDEPATH += \
../DollEngine/core \
../DollEngine/core/Base \
../DollEngine/core/Component \
../DollEngine/core/Data/CoreType \
../DollEngine/core/Data/FileUnits \
../DollEngine/core/Data/ImageUnits \
../DollEngine/core/EventManager \
../DollEngine/core/KAGParser \
../DollEngine/core/Painter \
../DollEngine/core/Painter/Program \
../DollEngine/core/Scripts \
../DollEngine/core/Scripts/TjsExtra \
../DollEngine/core/Widget \
../DollEngine/core/Interface \
../DollEngine/lib/freetype2 \
../DollEngine/lib/kazmath/include/kazmath \

SOURCES += main.cpp\
        Console.cpp \ 
    ../DollEngine/core/base/AppInfo.cpp \
    ../DollEngine/core/base/Debug.cpp \
    ../DollEngine/core/base/Status.cpp \
    ../DollEngine/core/base/Storages.cpp \
    ../DollEngine/core/base/System.cpp \
    ../DollEngine/core/component/Character.cpp \
    ../DollEngine/core/component/Component.cpp \
    ../DollEngine/core/component/Painter.cpp \
    ../DollEngine/core/component/RTT.cpp \
    ../DollEngine/core/component/Timer.cpp \
    ../DollEngine/core/component/TouchListener.cpp \
    ../DollEngine/core/Data/CoreType/Color.cpp \
    ../DollEngine/core/Data/CoreType/Transform.cpp \
    ../DollEngine/core/Data/CoreType/Types.cpp \
    ../DollEngine/core/Data/fileUnits/FileInfo.cpp \
    ../DollEngine/core/Data/fileUnits/IOData.cpp \
    ../DollEngine/core/Data/imageUnits/GLCache.cpp \
    ../DollEngine/core/Data/imageUnits/GLTexture.cpp \
    ../DollEngine/core/Data/imageUnits/ImageData.cpp \
    ../DollEngine/core/Data/imageUnits/SpriteFrame.cpp \
    ../DollEngine/core/Data/imageUnits/TextFrame.cpp \
    ../DollEngine/core/EventManager/CompManager.cpp \
    ../DollEngine/core/KAGParser/KAGController.cpp \
    ../DollEngine/core/KAGParser/KAGLabel.cpp \
    ../DollEngine/core/KAGParser/KAGParser.cpp \
    ../DollEngine/core/KAGParser/KAGStorage.cpp \
    ../DollEngine/core/KAGParser/KAGTag.cpp \
    ../DollEngine/core/painter/program/GLProgram.cpp \
    ../DollEngine/core/painter/program/GrowProgram.cpp \
    ../DollEngine/core/painter/program/NormalProgram.cpp \
    ../DollEngine/core/painter/GLCanvas.cpp \
    ../DollEngine/core/painter/GLShaderObject.cpp \
    ../DollEngine/core/scripts/tjsextra/TjsDictIterator.cpp \
    ../DollEngine/core/scripts/tjsextra/TjsSet.cpp \
    ../DollEngine/core/scripts/JsonParser.cpp \
    ../DollEngine/core/scripts/ScriptEngine.cpp \
    ../DollEngine/core/scripts/TjsBind.cpp \
    ../DollEngine/core/widget/TjsConsole.cpp \
    ../DollEngine/core/widget/Window.cpp \
    ../DollEngine/core/CoreUnits.cpp \
    ../DollEngine/lib/msg/apple/MsgLoad.cpp \
    ../DollEngine/lib/msg/text/MsgLoad.cpp \
    ../DollEngine/lib/ncbind/ncbind.cpp \
    ../DollEngine/lib/tjs2/tjs.cpp \
    ../DollEngine/lib/tjs2/tjs.tab.cpp \
    ../DollEngine/lib/tjs2/tjsArray.cpp \
    ../DollEngine/lib/tjs2/tjsBinarySerializer.cpp \
    ../DollEngine/lib/tjs2/tjsByteCodeLoader.cpp \
    ../DollEngine/lib/tjs2/tjsCompileControl.cpp \
    ../DollEngine/lib/tjs2/tjsConfig.cpp \
    ../DollEngine/lib/tjs2/tjsConstArrayData.cpp \
    ../DollEngine/lib/tjs2/tjsDate.cpp \
    ../DollEngine/lib/tjs2/tjsdate.tab.cpp \
    ../DollEngine/lib/tjs2/tjsDateParser.cpp \
    ../DollEngine/lib/tjs2/tjsDateWordMap.cc \
    ../DollEngine/lib/tjs2/tjsDebug.cpp \
    ../DollEngine/lib/tjs2/tjsDictionary.cpp \
    ../DollEngine/lib/tjs2/tjsDisassemble.cpp \
    ../DollEngine/lib/tjs2/tjsError.cpp \
    ../DollEngine/lib/tjs2/tjsException.cpp \
    ../DollEngine/lib/tjs2/tjsGlobalStringMap.cpp \
    ../DollEngine/lib/tjs2/tjsInterCodeExec.cpp \
    ../DollEngine/lib/tjs2/tjsInterCodeGen.cpp \
    ../DollEngine/lib/tjs2/tjsInterface.cpp \
    ../DollEngine/lib/tjs2/tjsLex.cpp \
    ../DollEngine/lib/tjs2/tjsMath.cpp \
    ../DollEngine/lib/tjs2/tjsMessage.cpp \
    ../DollEngine/lib/tjs2/tjsMT19937ar-cok.cpp \
    ../DollEngine/lib/tjs2/tjsNamespace.cpp \
    ../DollEngine/lib/tjs2/tjsNative.cpp \
    ../DollEngine/lib/tjs2/tjsObject.cpp \
    ../DollEngine/lib/tjs2/tjsObjectExtendable.cpp \
    ../DollEngine/lib/tjs2/tjsOctPack.cpp \
    ../DollEngine/lib/tjs2/tjspp.tab.cpp \
    ../DollEngine/lib/tjs2/tjsRandomGenerator.cpp \
    ../DollEngine/lib/tjs2/tjsRegExp.cpp \
    ../DollEngine/lib/tjs2/tjsScriptBlock.cpp \
    ../DollEngine/lib/tjs2/tjsScriptCache.cpp \
    ../DollEngine/lib/tjs2/tjsString.cpp \
    ../DollEngine/lib/tjs2/tjsUtils.cpp \
    ../DollEngine/lib/tjs2/tjsVariant.cpp \
    ../DollEngine/lib/tjs2/tjsVariantString.cpp \
    ../DollEngine/lib/kazmath/src/GL/mat4stack.c \
    ../DollEngine/lib/kazmath/src/GL/matrix.c \
    ../DollEngine/lib/kazmath/src/aabb.c \
    ../DollEngine/lib/kazmath/src/mat3.c \
    ../DollEngine/lib/kazmath/src/mat4.c \
    ../DollEngine/lib/kazmath/src/neon_matrix_impl.c \
    ../DollEngine/lib/kazmath/src/plane.c \
    ../DollEngine/lib/kazmath/src/quaternion.c \
    ../DollEngine/lib/kazmath/src/ray2.c \
    ../DollEngine/lib/kazmath/src/utility.c \
    ../DollEngine/lib/kazmath/src/vec2.c \
    ../DollEngine/lib/kazmath/src/vec3.c \
    ../DollEngine/lib/kazmath/src/vec4.c \
    ../DollEngine/lib/onig/enc/ascii.c \
    ../DollEngine/lib/onig/enc/big5.c \
    ../DollEngine/lib/onig/enc/cp1251.c \
    ../DollEngine/lib/onig/enc/euc_jp.c \
    ../DollEngine/lib/onig/enc/euc_kr.c \
    ../DollEngine/lib/onig/enc/euc_tw.c \
    ../DollEngine/lib/onig/enc/gb18030.c \
    ../DollEngine/lib/onig/enc/iso8859_1.c \
    ../DollEngine/lib/onig/enc/iso8859_10.c \
    ../DollEngine/lib/onig/enc/iso8859_11.c \
    ../DollEngine/lib/onig/enc/iso8859_13.c \
    ../DollEngine/lib/onig/enc/iso8859_14.c \
    ../DollEngine/lib/onig/enc/iso8859_15.c \
    ../DollEngine/lib/onig/enc/iso8859_16.c \
    ../DollEngine/lib/onig/enc/iso8859_2.c \
    ../DollEngine/lib/onig/enc/iso8859_3.c \
    ../DollEngine/lib/onig/enc/iso8859_4.c \
    ../DollEngine/lib/onig/enc/iso8859_5.c \
    ../DollEngine/lib/onig/enc/iso8859_6.c \
    ../DollEngine/lib/onig/enc/iso8859_7.c \
    ../DollEngine/lib/onig/enc/iso8859_8.c \
    ../DollEngine/lib/onig/enc/iso8859_9.c \
    ../DollEngine/lib/onig/enc/koi8.c \
    ../DollEngine/lib/onig/enc/koi8_r.c \
    ../DollEngine/lib/onig/enc/mktable.c \
    ../DollEngine/lib/onig/enc/sjis.c \
    ../DollEngine/lib/onig/enc/unicode.c \
    ../DollEngine/lib/onig/enc/utf16_be.c \
    ../DollEngine/lib/onig/enc/utf16_le.c \
    ../DollEngine/lib/onig/enc/utf32_be.c \
    ../DollEngine/lib/onig/enc/utf32_le.c \
    ../DollEngine/lib/onig/enc/utf8.c \
    ../DollEngine/lib/onig/win32/testc.c \
    ../DollEngine/lib/onig/regcomp.c \
    ../DollEngine/lib/onig/regenc.c \
    ../DollEngine/lib/onig/regerror.c \
    ../DollEngine/lib/onig/regexec.c \
    ../DollEngine/lib/onig/regext.c \
    ../DollEngine/lib/onig/reggnu.c \
    ../DollEngine/lib/onig/regparse.c \
    ../DollEngine/lib/onig/regposerr.c \
    ../DollEngine/lib/onig/regposix.c \
    ../DollEngine/lib/onig/regsyntax.c \
    ../DollEngine/lib/onig/regtrav.c \
    ../DollEngine/lib/onig/regversion.c \
    ../DollEngine/lib/onig/st.c \
    ../DollEngine/core/platform/qt/DrawInterface-Qt.cpp \
    ../DollEngine/core/platform/qt/FontInterface-Qt.cpp \
    ../DollEngine/core/Data/CoreType/CoreString.cpp

HEADERS  += Console.h \
    ../DollEngine/core/base/AppInfo.h \
    ../DollEngine/core/base/Debug.h \
    ../DollEngine/core/base/Status.h \
    ../DollEngine/core/base/Storages.h \
    ../DollEngine/core/base/System.h \
    ../DollEngine/core/component/Audio.h \
    ../DollEngine/core/component/Character.h \
    ../DollEngine/core/component/Component.h \
    ../DollEngine/core/component/Painter.h \
    ../DollEngine/core/component/RTT.h \
    ../DollEngine/core/component/Timer.h \
    ../DollEngine/core/component/TouchListener.h \
    ../DollEngine/core/Data/CoreType/Color.h \
    ../DollEngine/core/Data/CoreType/Transform.h \
    ../DollEngine/core/Data/CoreType/Types.h \
    ../DollEngine/core/Data/fileUnits/FileInfo.h \
    ../DollEngine/core/Data/fileUnits/IOData.h \
    ../DollEngine/core/Data/imageUnits/GLCache.h \
    ../DollEngine/core/Data/imageUnits/GLTexture.h \
    ../DollEngine/core/Data/imageUnits/ImageData.h \
    ../DollEngine/core/Data/imageUnits/SpriteFrame.h \
    ../DollEngine/core/Data/imageUnits/TextFrame.h \
    ../DollEngine/core/EventManager/CompManager.h \
    ../DollEngine/core/KAGParser/KAGController.h \
    ../DollEngine/core/KAGParser/KAGLabel.h \
    ../DollEngine/core/KAGParser/KAGParser.h \
    ../DollEngine/core/KAGParser/KAGStorage.h \
    ../DollEngine/core/KAGParser/KAGTag.h \
    ../DollEngine/core/painter/program/GLProgram.h \
    ../DollEngine/core/painter/program/GrowProgram.h \
    ../DollEngine/core/painter/program/NormalProgram.h \
    ../DollEngine/core/painter/GLCanvas.h \
    ../DollEngine/core/painter/GLShaderObject.h \
    ../DollEngine/core/scripts/tjsextra/TjsDictIterator.h \
    ../DollEngine/core/scripts/tjsextra/TjsSet.h \
    ../DollEngine/core/scripts/JsonParser.h \
    ../DollEngine/core/scripts/ScriptEngine.h \
    ../DollEngine/core/scripts/TjsBind.h \
    ../DollEngine/core/widget/TjsConsole.h \
    ../DollEngine/core/widget/Window.h \
    ../DollEngine/core/CoreMacros.h \
    ../DollEngine/core/CoreUnits.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/config/ftconfig.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/config/ftheader.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/config/ftmodule.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/config/ftoption.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/config/ftstdlib.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svbdf.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svcid.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svgldict.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svgxval.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svkern.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svmm.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svotval.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svpfr.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svpostnm.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svprop.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svpscmap.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svpsinfo.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svsfnt.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svttcmap.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svtteng.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svttglyf.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svwinfnt.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/services/svxf86nm.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/autohint.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/ftcalc.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/ftdebug.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/ftdriver.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/ftgloadr.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/ftmemory.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/ftobjs.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/ftpic.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/ftrfork.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/ftserv.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/ftstream.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/fttrace.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/ftvalid.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/internal.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/psaux.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/pshints.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/sfnt.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/t1types.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/internal/tttypes.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/freetype.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftadvanc.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftautoh.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftbbox.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftbdf.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftbitmap.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftbzip2.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftcache.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftcffdrv.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftchapters.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftcid.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/fterrdef.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/fterrors.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftgasp.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftglyph.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftgxval.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftgzip.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftimage.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftincrem.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftlcdfil.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftlist.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftlzw.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftmac.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftmm.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftmodapi.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftmoderr.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftotval.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftoutln.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftpfr.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftrender.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftsizes.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftsnames.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftstroke.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftsynth.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftsystem.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/fttrigon.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftttdrv.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/fttypes.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftwinfnt.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ftxf86.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/t1tables.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ttnameid.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/tttables.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/tttags.h \
    ../DollEngine/lib/freetype2/include/ios/freetype/ttunpat.h \
    ../DollEngine/lib/freetype2/include/ios/ft2build.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/config/ftconfig.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/config/ftheader.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/config/ftmodule.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/config/ftoption.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/config/ftstdlib.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svbdf.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svcid.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svgldict.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svgxval.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svkern.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svmm.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svotval.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svpfr.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svpostnm.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svprop.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svpscmap.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svpsinfo.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svsfnt.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svttcmap.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svtteng.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svttglyf.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svwinfnt.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/services/svxf86nm.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/autohint.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/ftcalc.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/ftdebug.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/ftdriver.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/ftgloadr.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/ftmemory.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/ftobjs.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/ftpic.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/ftrfork.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/ftserv.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/ftstream.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/fttrace.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/ftvalid.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/internal.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/psaux.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/pshints.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/sfnt.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/t1types.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/internal/tttypes.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/freetype.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftadvanc.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftautoh.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftbbox.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftbdf.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftbitmap.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftbzip2.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftcache.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftcffdrv.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftchapters.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftcid.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/fterrdef.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/fterrors.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftgasp.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftglyph.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftgxval.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftgzip.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftimage.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftincrem.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftlcdfil.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftlist.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftlzw.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftmac.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftmm.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftmodapi.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftmoderr.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftotval.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftoutln.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftpfr.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftrender.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftsizes.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftsnames.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftstroke.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftsynth.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftsystem.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/fttrigon.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftttdrv.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/fttypes.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftwinfnt.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ftxf86.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/t1tables.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ttnameid.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/tttables.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/tttags.h \
    ../DollEngine/lib/freetype2/include/mac/freetype/ttunpat.h \
    ../DollEngine/lib/freetype2/include/mac/ft2build.h \
    ../DollEngine/lib/kazmath/include/kazmath/GL/mat4stack.h \
    ../DollEngine/lib/kazmath/include/kazmath/GL/matrix.h \
    ../DollEngine/lib/kazmath/include/kazmath/aabb.h \
    ../DollEngine/lib/kazmath/include/kazmath/kazmath.h \
    ../DollEngine/lib/kazmath/include/kazmath/mat3.h \
    ../DollEngine/lib/kazmath/include/kazmath/mat4.h \
    ../DollEngine/lib/kazmath/include/kazmath/neon_matrix_impl.h \
    ../DollEngine/lib/kazmath/include/kazmath/plane.h \
    ../DollEngine/lib/kazmath/include/kazmath/quaternion.h \
    ../DollEngine/lib/kazmath/include/kazmath/ray2.h \
    ../DollEngine/lib/kazmath/include/kazmath/utility.h \
    ../DollEngine/lib/kazmath/include/kazmath/vec2.h \
    ../DollEngine/lib/kazmath/include/kazmath/vec3.h \
    ../DollEngine/lib/kazmath/include/kazmath/vec4.h \
    ../DollEngine/lib/msg/apple/string_table_en.h \
    ../DollEngine/lib/msg/apple/string_table_jp.h \
    ../DollEngine/lib/msg/apple/string_table_resource.h \
    ../DollEngine/lib/msg/text/string_table_en.h \
    ../DollEngine/lib/msg/text/string_table_jp.h \
    ../DollEngine/lib/msg/text/string_table_resource.h \
    ../DollEngine/lib/msg/text/tjsErrorInc.h \
    ../DollEngine/lib/ncbind/ncb_foreach.h \
    ../DollEngine/lib/ncbind/ncb_invoke.hpp \
    ../DollEngine/lib/ncbind/ncbind.hpp \
    ../DollEngine/lib/onig/config.h \
    ../DollEngine/lib/onig/oniggnu.h \
    ../DollEngine/lib/onig/onigposix.h \
    ../DollEngine/lib/onig/oniguruma.h \
    ../DollEngine/lib/onig/regenc.h \
    ../DollEngine/lib/onig/regint.h \
    ../DollEngine/lib/onig/regparse.h \
    ../DollEngine/lib/onig/st.h \
    ../DollEngine/lib/tjs/include/ncb_foreach.h \
    ../DollEngine/lib/tjs/include/ncb_invoke.hpp \
    ../DollEngine/lib/tjs/include/ncbind.hpp \
    ../DollEngine/lib/tjs/include/tjs.h \
    ../DollEngine/lib/tjs/include/tjsArray.h \
    ../DollEngine/lib/tjs/include/tjsBinarySerializer.h \
    ../DollEngine/lib/tjs/include/tjsByteCodeLoader.h \
    ../DollEngine/lib/tjs/include/tjsCommHead.h \
    ../DollEngine/lib/tjs/include/tjsCompileControl.h \
    ../DollEngine/lib/tjs/include/tjsConfig.h \
    ../DollEngine/lib/tjs/include/tjsConstArrayData.h \
    ../DollEngine/lib/tjs/include/tjsDate.h \
    ../DollEngine/lib/tjs/include/tjsdate.tab.h \
    ../DollEngine/lib/tjs/include/tjsDateParser.h \
    ../DollEngine/lib/tjs/include/tjsDebug.h \
    ../DollEngine/lib/tjs/include/tjsDictionary.h \
    ../DollEngine/lib/tjs/include/tjsError.h \
    ../DollEngine/lib/tjs/include/tjsErrorDefs.h \
    ../DollEngine/lib/tjs/include/tjsErrorInc.h \
    ../DollEngine/lib/tjs/include/tjsException.h \
    ../DollEngine/lib/tjs/include/tjsGlobalStringMap.h \
    ../DollEngine/lib/tjs/include/tjsHashSearch.h \
    ../DollEngine/lib/tjs/include/tjsInterCodeExec.h \
    ../DollEngine/lib/tjs/include/tjsInterCodeGen.h \
    ../DollEngine/lib/tjs/include/tjsInterface.h \
    ../DollEngine/lib/tjs/include/tjsLex.h \
    ../DollEngine/lib/tjs/include/tjsMath.h \
    ../DollEngine/lib/tjs/include/tjsMessage.h \
    ../DollEngine/lib/tjs/include/tjsMT19937ar-cok.h \
    ../DollEngine/lib/tjs/include/tjsNamespace.h \
    ../DollEngine/lib/tjs/include/tjsNative.h \
    ../DollEngine/lib/tjs/include/tjsObject.h \
    ../DollEngine/lib/tjs/include/tjsObjectExtendable.h \
    ../DollEngine/lib/tjs/include/tjsOctPack.h \
    ../DollEngine/lib/tjs/include/tjspp.tab.h \
    ../DollEngine/lib/tjs/include/tjsRandomGenerator.h \
    ../DollEngine/lib/tjs/include/tjsRegExp.h \
    ../DollEngine/lib/tjs/include/tjsScriptBlock.h \
    ../DollEngine/lib/tjs/include/tjsScriptCache.h \
    ../DollEngine/lib/tjs/include/tjsString.h \
    ../DollEngine/lib/tjs/include/tjsTypes.h \
    ../DollEngine/lib/tjs/include/tjsUtils.h \
    ../DollEngine/lib/tjs/include/tjsVariant.h \
    ../DollEngine/lib/tjs/include/tjsVariantString.h \
    ../DollEngine/lib/tjs2/tjs.h \
    ../DollEngine/lib/tjs2/tjs.tab.h \
    ../DollEngine/lib/tjs2/tjs.tab.hpp \
    ../DollEngine/lib/tjs2/tjsArray.h \
    ../DollEngine/lib/tjs2/tjsBinarySerializer.h \
    ../DollEngine/lib/tjs2/tjsByteCodeLoader.h \
    ../DollEngine/lib/tjs2/tjsCommHead.h \
    ../DollEngine/lib/tjs2/tjsCompileControl.h \
    ../DollEngine/lib/tjs2/tjsConfig.h \
    ../DollEngine/lib/tjs2/tjsConstArrayData.h \
    ../DollEngine/lib/tjs2/tjsDate.h \
    ../DollEngine/lib/tjs2/tjsdate.tab.h \
    ../DollEngine/lib/tjs2/tjsdate.tab.hpp \
    ../DollEngine/lib/tjs2/tjsDateParser.h \
    ../DollEngine/lib/tjs2/tjsDebug.h \
    ../DollEngine/lib/tjs2/tjsDictionary.h \
    ../DollEngine/lib/tjs2/tjsError.h \
    ../DollEngine/lib/tjs2/tjsErrorDefs.h \
    ../DollEngine/lib/tjs2/tjsErrorInc.h \
    ../DollEngine/lib/tjs2/tjsException.h \
    ../DollEngine/lib/tjs2/tjsGlobalStringMap.h \
    ../DollEngine/lib/tjs2/tjsHashSearch.h \
    ../DollEngine/lib/tjs2/tjsInterCodeExec.h \
    ../DollEngine/lib/tjs2/tjsInterCodeGen.h \
    ../DollEngine/lib/tjs2/tjsInterface.h \
    ../DollEngine/lib/tjs2/tjsLex.h \
    ../DollEngine/lib/tjs2/tjsMath.h \
    ../DollEngine/lib/tjs2/tjsMessage.h \
    ../DollEngine/lib/tjs2/tjsMT19937ar-cok.h \
    ../DollEngine/lib/tjs2/tjsNamespace.h \
    ../DollEngine/lib/tjs2/tjsNative.h \
    ../DollEngine/lib/tjs2/tjsObject.h \
    ../DollEngine/lib/tjs2/tjsObjectExtendable.h \
    ../DollEngine/lib/tjs2/tjsOctPack.h \
    ../DollEngine/lib/tjs2/tjspp.tab.h \
    ../DollEngine/lib/tjs2/tjspp.tab.hpp \
    ../DollEngine/lib/tjs2/tjsRandomGenerator.h \
    ../DollEngine/lib/tjs2/tjsRegExp.h \
    ../DollEngine/lib/tjs2/tjsScriptBlock.h \
    ../DollEngine/lib/tjs2/tjsScriptCache.h \
    ../DollEngine/lib/tjs2/tjsString.h \
    ../DollEngine/lib/tjs2/tjsTypes.h \
    ../DollEngine/lib/tjs2/tjsUtils.h \
    ../DollEngine/lib/tjs2/tjsVariant.h \
    ../DollEngine/lib/tjs2/tjsVariantString.h \
    ../DollEngine/core/Interface/DrawInterface.h \
    ../DollEngine/core/Interface/FontInterface.h \
    ../DollEngine/core/Data/CoreType/CoreString.h

FORMS    += Console.ui

