// generated from gentext.pl Messages.xlsx
#ifndef __STRING_TABLE_EN_H__
#define __STRING_TABLE_EN_H__
#define IDS_TJS_INTERNAL_ERROR_                                                    L"Internal error"
#define IDS_TJS_WARNING_                                                           L"Warning: "
#define IDS_TJS_WARN_EVAL_OPERATOR_                                                L"Non-global post-! operator is used (note that the post-! operator behavior is changed on TJS2 version 2.4.1)"
#define IDS_TJS_NARROW_TO_WIDE_CONVERSION_ERROR_                                   L"Cannot convert given narrow string to wide string"
#define IDS_TJS_VARIANT_CONVERT_ERROR_                                             L"Cannot convert the variable type (%1 to %2)"
#define IDS_TJS_VARIANT_CONVERT_ERROR_TO_OBJECT_                                   L"Cannot convert the variable type (%1 to Object)"
#define IDS_TJS_IDEXPECTED_                                                        L"Specify an ID"
#define IDS_TJS_SUBSTITUTION_IN_BOOLEAN_CONTEXT_                                   L"Substitution in boolean context (use form of \'(A=B)!=0\' to compare to zero)"
#define IDS_TJS_CANNOT_MODIFY_LHS_                                                 L"This expression cannot be used as a lvalue"
#define IDS_TJS_INSUFFICIENT_MEM_                                                  L"Insufficient memory"
#define IDS_TJS_CANNOT_GET_RESULT_                                                 L"Cannot get the value of this expression"
#define IDS_TJS_NULL_ACCESS_                                                       L"Accessing to null object"
#define IDS_TJS_MEMBER_NOT_FOUND_                                                  L"Member \"%1\" does not exist"
#define IDS_TJS_MEMBER_NOT_FOUND_NO_NAME_GIVEN_                                    L"Member does not exist"
#define IDS_TJS_NOT_IMPLEMENTED_                                                   L"Called method is not implemented"
#define IDS_TJS_INVALID_PARAM_                                                     L"Invalid argument"
#define IDS_TJS_BAD_PARAM_COUNT_                                                   L"Invalid argument count"
#define IDS_TJS_INVALID_TYPE_                                                      L"Not a function or invalid method/property type"
#define IDS_TJS_SPECIFY_DIC_OR_ARRAY_                                              L"Specify a Dictionary object or an Array object"
#define IDS_TJS_SPECIFY_ARRAY_                                                     L"Specify an Array object"
#define IDS_TJS_STRING_DEALLOC_ERROR_                                              L"Cannot free the string memory block"
#define IDS_TJS_STRING_ALLOC_ERROR_                                                L"Cannot allocate the string memory block"
#define IDS_TJS_MISPLACED_BREAK_CONTINUE_                                          L"Cannot place \"break\" or \"continue\" here"
#define IDS_TJS_MISPLACED_CASE_                                                    L"Cannot place \"case\" here"
#define IDS_TJS_MISPLACED_RETURN_                                                  L"Cannot place \"return\" here"
#define IDS_TJS_STRING_PARSE_ERROR_                                                L"Un-terminated string/regexp/octet literal"
#define IDS_TJS_NUMBER_ERROR_                                                      L"Cannot be parsed as a number"
#define IDS_TJS_UNCLOSED_COMMENT_                                                  L"Un-terminated comment"
#define IDS_TJS_INVALID_CHAR_                                                      L"Invalid character \'%1\'"
#define IDS_TJS_EXPECTED_                                                          L"Expected %1"
#define IDS_TJS_SYNTAX_ERROR_                                                      L"Syntax error (%1)"
#define IDS_TJS_PPERROR_                                                           L"Error in conditional compiling expression"
#define IDS_TJS_CANNOT_GET_SUPER_                                                  L"Super class does not exist or cannot specify the super class"
#define IDS_TJS_INVALID_OPECODE_                                                   L"Invalid VM code"
#define IDS_TJS_RANGE_ERROR_                                                       L"The value is out of the range"
#define IDS_TJS_ACCESS_DENYED_                                                     L"Invalid operation for Read-only or Write-only property"
#define IDS_TJS_NATIVE_CLASS_CRASH_                                                L"Invalid object context"
#define IDS_TJS_INVALID_OBJECT_                                                    L"The object is already invalidated"
#define IDS_TJS_CANNOT_OMIT_                                                       L"\"...\" is used out of functions"
#define IDS_TJS_CANNOT_PARSE_DATE_                                                 L"Invalid date format"
#define IDS_TJS_INVALID_VALUE_FOR_TIMESTAMP_                                       L"Invalid value for date/time"
#define IDS_TJS_EXCEPTION_NOT_FOUND_                                               L"Cannot convert exception because \"Exception\" does not exist"
#define IDS_TJS_INVALID_FORMAT_STRING_                                             L"Invalid format string"
#define IDS_TJS_DIVIDE_BY_ZERO_                                                    L"Division by zero"
#define IDS_TJS_NOT_RECONSTRUCTIVE_RANDOMIZE_DATA_                                 L"Cannot reconstruct random seeds"
#define IDS_TJS_SYMBOL_                                                            L"ID"
#define IDS_TJS_CALL_HISTORY_IS_FROM_OUT_OF_TJS2SCRIPT_                            L"[out of TJS2 script]"
#define IDS_TJS_NOBJECTS_WAS_NOT_FREED_                                            L"Total %1 Object(s) was not freed"
#define IDS_TJS_OBJECT_CREATION_HISTORY_DELIMITER_                                 L" <-- "
#define IDS_TJS_OBJECT_WAS_NOT_FREED_                                              L"Object %1 [%2] wes not freed / The object was created at : %2"
#define IDS_TJS_GROUP_BY_OBJECT_TYPE_AND_HISTORY_                                  L"Group by object type and location where the object was created"
#define IDS_TJS_GROUP_BY_OBJECT_TYPE_                                              L"Group by object type"
#define IDS_TJS_OBJECT_COUNTING_MESSAGE_GROUP_BY_OBJECT_TYPE_AND_HISTORY_          L"%1 time(s) : [%2] %3"
#define IDS_TJS_OBJECT_COUNTING_MESSAGE_TJSGROUP_BY_OBJECT_TYPE_                   L"%1 time(s) : [%2]"
#define IDS_TJS_WARN_RUNNING_CODE_ON_DELETING_OBJECT_                              L"%4: Running code on deleting-in-progress object %1[%2] / The object was created at : %3"
#define IDS_TJS_WRITE_ERROR_                                                       L"Write error"
#define IDS_TJS_READ_ERROR_                                                        L"Read error"
#define IDS_TJS_SEEK_ERROR_                                                        L"Seek error"
#define IDS_TJS_BYTE_CODE_BROKEN_                                                  L"Bytecode read error. File is broken or it\'s not bytecode file."
#define IDS_TJS_OBJECT_HASH_MAP_LOG_VERSION_MISMATCH_                              L"Object Hash Map log version mismatch"
#define IDS_TJS_CURRUPTED_OBJECT_HASH_MAP_LOG_                                     L"Currupted Object Hash Map log"
#define IDS_TJS_UNKNOWN_FAILURE_                                                   L"Unknown failure : %08X"
#define IDS_TJS_UNKNOWN_PACK_UNPACK_TEMPLATE_CHARCTER_                             L"Unknown pack/unpack TEMPLATE charcter"
#define IDS_TJS_UNKNOWN_BIT_STRING_CHARACTER_                                      L"Unknown bit string charcter"
#define IDS_TJS_UNKNOWN_HEX_STRING_CHARACTER_                                      L"Unknown Hex string charcter"
#define IDS_TJS_NOT_SUPPORTED_UUENCODE_                                            L"Not supported uuencode"
#define IDS_TJS_NOT_SUPPORTED_BER_                                                 L"Not supported BER"
#define IDS_TJS_NOT_SUPPORTED_UNPACK_LP_                                           L"Not supported unpack \'p\'"
#define IDS_TJS_NOT_SUPPORTED_UNPACK_P                                             L"Not supported unpack \'P\'"
#define IDS_TVP_VERSION_INFORMATION_                                               L"Kirikiri Z Executable core /%1 (Compiled on %DATE% %TIME%) TJS2/%2 Copyright (C) 1997-2013 W.Dee and contributors All rights reserved."
#define IDS_TVP_VERSION_INFORMATION2_                                              L"The details of version information can be perused if -about is attached and started. "
#define IDS_TVP_DOWNLOAD_PAGE_URL_                                                 L"http://krkrz.github.io/"
#define IDS_TVP_INTERNAL_ERROR_                                                    L"Internal Error: at %1 line %2"
#define IDS_TVP_INVALID_PARAM_                                                     L"Invalid Parameter"
#define IDS_TVP_WARN_DEBUG_OPTION_ENABLED_                                         L"Debug option enabled"
#define IDS_TVP_COMMAND_LINE_PARAM_IGNORED_AND_DEFAULT_USED_                       L"Command line parameter %1 = %2 is invalid. It\'s used default."
#define IDS_TVP_INVALID_COMMAND_LINE_PARAM_                                        L"Command line parameter %1 = %2 is invalid."
#define IDS_TVP_NOT_IMPLEMENTED_                                                   L"Not implemented"
#define IDS_TVP_CANNOT_OPEN_STORAGE_                                               L"Cannot open storage %1"
#define IDS_TVP_CANNOT_FIND_STORAGE_                                               L"Cannot find storage %1"
#define IDS_TVP_CANNOT_OPEN_STORAGE_FOR_WRITE_                                     L"Cannot open storage %1 for writing"
#define IDS_TVP_STORAGE_IN_ARCHIVE_NOT_FOUND_                                      L"Cannot find storage %1 in archive %2"
#define IDS_TVP_INVALID_PATH_NAME_                                                 L"Invalid path name %1"
#define IDS_TVP_UNSUPPORTED_MEDIA_NAME_                                            L"Not supported media type \"%1\""
#define IDS_TVP_CANNOT_UNBIND_XP3EXE_                                              L"Cannot unbind XP3 exe %1"
#define IDS_TVP_CANNOT_FIND_XP3MARK_                                               L"%1 is not XP3 archive or unsupported"
#define IDS_TVP_MISSING_PATH_DELIMITER_AT_LAST_                                    L"Use path delimiter \'>\' or \'/\'"
#define IDS_TVP_FILENAME_CONTAINS_SHARP_WARN_                                      L"(Attention) Filename \"%1\" contains \'#\'"
#define IDS_TVP_CANNOT_GET_LOCAL_NAME_                                             L"Cannot get local name from %1"
#define IDS_TVP_READ_ERROR_                                                        L"Read error"
#define IDS_TVP_WRITE_ERROR_                                                       L"Write error"
#define IDS_TVP_SEEK_ERROR_                                                        L"Seek error"
#define IDS_TVP_TRUNCATE_ERROR_                                                    L"Truncate error"
#define IDS_TVP_INSUFFICIENT_MEMORY_                                               L"Cannot allocate memory"
#define IDS_TVP_UNCOMPRESSION_FAILED_                                              L"Unpompression failed"
#define IDS_TVP_COMPRESSION_FAILED_                                                L"Compression failed"
#define IDS_TVP_CANNOT_WRITE_TO_ARCHIVE_                                           L"Cannot write to archive"
#define IDS_TVP_UNSUPPORTED_CIPHER_MODE_                                           L"%1 is unsupported cipger mode"
#define IDS_TVP_UNSUPPORTED_ENCODING_                                              L"%1 is unsupported encoding"
#define IDS_TVP_UNSUPPORTED_MODE_STRING_                                           L"%1 is unsupported mode string"
#define IDS_TVP_UNKNOWN_GRAPHIC_FORMAT_                                            L"Unknown graphic format %1"
#define IDS_TVP_CANNOT_SUGGEST_GRAPHIC_EXTENSION_                                  L"Cannot suggest graphics extension for %1"
#define IDS_TVP_MASK_SIZE_MISMATCH_                                                L"Mask size mismath"
#define IDS_TVP_PROVINCE_SIZE_MISMATCH_                                            L"Province image %1 size mismatch"
#define IDS_TVP_IMAGE_LOAD_ERROR_                                                  L"Image Load Error /%1"
#define IDS_TVP_JPEGLOAD_ERROR_                                                    L"JPEG Read Error /%1"
#define IDS_TVP_PNGLOAD_ERROR_                                                     L"PNG Read Error /%1"
#define IDS_TVP_ERILOAD_ERROR_                                                     L"ERI Read Error /%1"
#define IDS_TVP_TLGLOAD_ERROR_                                                     L"TLG Read Error /%1"
#define IDS_TVP_INVALID_IMAGE_SAVE_TYPE_                                           L"Invalid image save type (%1)"
#define IDS_TVP_INVALID_OPERATION_FOR8BPP_                                         L"Invalid operation for 8bpp"
#define IDS_TVP_INVALID_OPERATION_FOR32BPP_                                        L"Invalid operation for 32bpp"
#define IDS_TVP_SPECIFY_WINDOW_                                                    L"Specify Window class object"
#define IDS_TVP_SPECIFY_LAYER_                                                     L"Specify Layer class object"
#define IDS_TVP_SPECIFY_LAYER_OR_BITMAP_                                           L"Specify Layer or Bitmap class object"
#define IDS_TVP_CANNOT_ACCEPT_MODE_AUTO_                                           L"Cannot accept omAuto mode"
#define IDS_TVP_CANNOT_CREATE_EMPTY_LAYER_IMAGE_                                   L"Cannot create empty layer image"
#define IDS_TVP_CANNOT_SET_PRIMARY_INVISIBLE_                                      L"Cannot set primary layer invisible"
#define IDS_TVP_CANNOT_MOVE_PRIMARY_                                               L"Cannot move primary layer"
#define IDS_TVP_CANNOT_SET_PARENT_SELF_                                            L"Cannot set parent self"
#define IDS_TVP_CANNOT_MOVE_NEXT_TO_SELF_OR_NOT_SIBLINGS_                          L"Cannot move next to self or not siblings"
#define IDS_TVP_CANNOT_MOVE_PRIMARY_OR_SIBLINGLESS_                                L"Cannot move primary or siblingless"
#define IDS_TVP_CANNOT_MOVE_TO_UNDER_OTHER_PRIMARY_LAYER_                          L"Cannot move to under Other primary layer"
#define IDS_TVP_INVALID_IMAGE_POSITION_                                            L"Invalid Image position"
#define IDS_TVP_CANNOT_SET_MODE_TO_DISABLED_OR_MODAL_                              L"Cannot set Mode to disabled or modal"
#define IDS_TVP_NOT_DRAWABLE_LAYER_TYPE_                                           L"Not drawable layer type"
#define IDS_TVP_SOURCE_LAYER_HAS_NO_IMAGE_                                         L"Source layer has no image"
#define IDS_TVP_UNSUPPORTED_LAYER_TYPE_                                            L"Unsupported layer type %1"
#define IDS_TVP_NOT_DRAWABLE_FACE_TYPE_                                            L"Not drawble face type %1"
#define IDS_TVP_CANNOT_CONVERT_LAYER_TYPE_USING_GIVEN_DIRECTION_                   L"Cannot convert layer type using given direction"
#define IDS_TVP_NEGATIVE_OPACITY_NOT_SUPPORTED_ON_THIS_FACE_                       L"Negative opacity not supported on this face"
#define IDS_TVP_SRC_RECT_OUT_OF_BITMAP_                                            L"Source rectangle out of bitmap"
#define IDS_TVP_BOX_BLUR_AREA_MUST_CONTAIN_CENTER_PIXEL_                           L"Box blur area must contain center pixel"
#define IDS_TVP_BOX_BLUR_AREA_MUST_BE_SMALLER_THAN16MILLION_                       L"Box blur area must be smaller than 16 million"
#define IDS_TVP_CANNOT_CHANGE_FOCUS_IN_PROCESSING_FOCUS_                           L"Cannot change focus in processing focus"
#define IDS_TVP_WINDOW_HAS_NO_LAYER_                                               L"Window has no layer"
#define IDS_TVP_WINDOW_HAS_ALREADY_PRIMARY_LAYER_                                  L"Window has already primary layer"
#define IDS_TVP_SPECIFIED_EVENT_NEEDS_PARAMETER_                                   L"Specified event %1 needs parameter"
#define IDS_TVP_SPECIFIED_EVENT_NEEDS_PARAMETER2_                                  L"Specified event %1 needs parameter %2"
#define IDS_TVP_SPECIFIED_EVENT_NAME_IS_UNKNOWN_                                   L"Specified event name %1 is unknown"
#define IDS_TVP_OUT_OF_RECTANGLE_                                                  L"Out of Rectangle"
#define IDS_TVP_INVALID_METHOD_IN_UPDATING_                                        L"Invalid method in updating"
#define IDS_TVP_CANNOT_CREATE_INSTANCE_                                            L"Cannot create instance"
#define IDS_TVP_UNKNOWN_WAVE_FORMAT_                                               L"Unknown wave format %1"
#define IDS_TVP_CURRENT_TRANSITION_MUST_BE_STOPPING_                               L"Current transition must be stopping"
#define IDS_TVP_TRANS_HANDLER_ERROR_                                               L"Transition handler error %1"
#define IDS_TVP_TRANS_ALREADY_REGISTERED_                                          L"Transition %1 already registerd"
#define IDS_TVP_CANNOT_FIND_TRANS_HANDER_                                          L"Cannot find transition handler %1"
#define IDS_TVP_SPECIFY_TRANSITION_SOURCE_                                         L"Specify transition source"
#define IDS_TVP_LAYER_CANNOT_HAVE_IMAGE_                                           L"This layer cannot have image"
#define IDS_TVP_TRANSITION_SOURCE_AND_DESTINATION_MUST_HAVE_IMAGE_                 L"Transition source and destination must have image"
#define IDS_TVP_CANNOT_LOAD_RULE_GRAPHIC_                                          L"Cannot load rule graphics %1"
#define IDS_TVP_SPECIFY_OPTION_                                                    L"Specify option %1"
#define IDS_TVP_TRANSITION_LAYER_SIZE_MISMATCH_                                    L"Transition layer size mismatch %1 and %2"
#define IDS_TVP_TRANSITION_MUTUAL_SOURCE_                                          L"Transition mutual source"
#define IDS_TVP_HOLD_DESTINATION_ALPHA_PARAMETER_IS_NOW_DEPRECATED_                L"Warring : Method %1 %2th parameter had is ignore. Hold destination alpha parameter is now deprecated."
#define IDS_TVP_CANNOT_CONNECT_MULTIPLE_WAVE_SOUND_BUFFER_AT_ONCE_                 L"Cannot connect multiple wave sound buffer at once"
#define IDS_TVP_INVALID_WINDOW_SIZE_MUST_BE_IN64TO32768_                           L"Invalid window size must be in 64 to 32768"
#define IDS_TVP_INVALID_OVERLAP_COUNT_MUST_BE_IN2TO32_                             L"Invalid overlap count must be in 2 to 32"
#define IDS_TVP_CURRENTLY_ASYNC_LOAD_BITMAP_                                       L"Currently async load bitmap"
#define IDS_TVP_FAILD_CLIPBOARD_COPY_                                              L"copying to clipboard failed."
#define IDS_TVP_INVALID_UTF16TO_UTF8_                                              L"Invalid UTF-16 to UTF-8"
#define IDS_TVP_INFO_LOADING_STARTUP_SCRIPT_                                       L"(info) Loading startup script : "
#define IDS_TVP_INFO_STARTUP_SCRIPT_ENDED_                                         L"(info) Startup script ended."
#define IDS_TVP_TJS_CHAR_MUST_BE_TWO_OR_FOUR_                                      L"sizeof(tjs_char) must be 2 or 4."
#define IDS_TVP_MEDIA_NAME_HAD_ALREADY_BEEN_REGISTERED_                            L"Media name \"%1\" had already been registered"
#define IDS_TVP_MEDIA_NAME_IS_NOT_REGISTERED_                                      L"Media name \"%1\" is not registered"
#define IDS_TVP_INFO_REBUILDING_AUTO_PATH_                                         L"(info) Rebuilding Auto Path Table ..."
#define IDS_TVP_INFO_TOTAL_FILE_FOUND_AND_ACTIVATED_                               L"(info) Total %1 file(s) found, %2 file(s) activated. (%3ms)"
#define IDS_TVP_ERROR_IN_RETRIEVING_SYSTEM_ON_ACTIVATE_ON_DEACTIVATE_              L"Error in retrieving System.onActivate/onDeactivate : %1"
#define IDS_TVP_THE_HOST_IS_NOT_A16BIT_UNICODE_SYSTEM_                             L"The host is not a 16-bit unicode system."
#define IDS_TVP_INFO_TRYING_TO_READ_XP3VIRTUAL_FILE_SYSTEM_INFORMATION_FROM_       L"(info) Trying to read XP3 virtual file system information from : %1"
#define IDS_TVP_SPECIFIED_STORAGE_HAD_BEEN_PROTECTED_                              L"Specified storage had been protected!"
#define IDS_TVP_INFO_FAILED_                                                       L"(info) Failed."
#define IDS_TVP_INFO_DONE_WITH_CONTAINS_                                           L"(info) Done. (contains %1 file(s), %2 segment(s))"
#define IDS_TVP_SEPARATOR_CRLF_                                                    L"\r\n\r\n\r\n==============================================================================\r\n==============================================================================\r\n"
#define IDS_TVP_SEPARATOR_CR_                                                      L"\n\n\n==============================================================================\n==============================================================================\n"
#define IDS_TVP_DEFAULT_FONT_NAME_                                                 L"MS Sans Serif"
#define IDS_TVP_CANNOT_OPEN_FONT_FILE_                                             L"Can\'t open font file \'%1$s\'"
#define IDS_TVP_FONT_CANNOT_BE_USED_                                               L"Font \'%1$s\' cannot be used"
#define IDS_TVP_FONT_RASTERIZE_ERROR_                                              L"Font Rasterize error."
#define IDS_TVP_BIT_FIELDS_NOT_SUPPORTED_                                          L"BITFIELDS not supported."
#define IDS_TVP_COMPRESSED_BMP_NOT_SUPPORTED_                                      L"Compressed BMP not supported."
#define IDS_TVP_UNSUPPORTED_COLOR_MODE_FOR_PALETT_IMAGE_                           L"Unsupported color mode for palettized image."
#define IDS_TVP_NOT_WINDOWS_BMP_                                                   L"This is not a Windows BMP file or an OS/2 BMP file."
#define IDS_TVP_UNSUPPORTED_HEADER_VERSION_                                        L"Non-supported header version."
#define IDS_TVP_INFO_TOUCHING_                                                     L"(info) Touching "
#define IDS_TVP_ABORTED_TIME_OUT_                                                  L" ... aborted [timed out]"
#define IDS_TVP_ABORTED_LIMIT_BYTE_                                                L" ... aborted [limit bytes exceeded]"
#define IDS_TVP_FAILD_GLYPH_FOR_DRAW_GLYPH_                                        L"Faild glyph for DrawGlyph."
#define IDS_TVP_LAYER_OBJECT_IS_NOT_PROPERLY_CONSTRUCTED_                          L"Panic! Layer object is not properly constructed. The constructor was not called??"
#define IDS_TVP_UNKNOWN_UPDATE_TYPE_                                               L"Unknown update type"
#define IDS_TVP_UNKNOWN_TRANSITION_TYPE_                                           L"Unknown transition type"
#define IDS_TVP_UNSUPPORTED_UPDATE_TYPE_TUT_GIVE_UPDATE_                           L"Update type of tutGiveUpdate is not yet supported"
#define IDS_TVP_ERROR_CODE_                                                        L"error code : "
#define IDS_TVP_UNSUPPORTED_JPEG_PALETTE_                                          L"JPEG does not support palettized image"
#define IDS_TVP_LIBPNG_ERROR_                                                      L"libpng error."
#define IDS_TVP_UNSUPPORTED_COLOR_TYPE_PALETTE_                                    L"Unsupported color type for palattized image"
#define IDS_TVP_UNSUPPORTED_COLOR_TYPE_                                            L"Unsupported color type"
#define IDS_TVP_TOO_LARGE_IMAGE_                                                   L"Too large image"
#define IDS_TVP_PNG_SAVE_ERROR_                                                    L"PNG save error."
#define IDS_TVP_TLG_UNSUPPORTED_UNIVERSAL_TRANSITION_RULE_                         L"TLG cannot be used as universal transition rule, province(_p) or mask(_m) images."
#define IDS_TVP_UNSUPPORTED_COLOR_COUNT_                                           L"Unsupported color count : "
#define IDS_TVP_DATA_FLAG_MUST_BE_ZERO_                                            L"Data flag must be 0 (any flags are not yet supported)"
#define IDS_TVP_UNSUPPORTED_COLOR_TYPE_COLON_                                      L"Unsupported color type : "
#define IDS_TVP_UNSUPPORTED_EXTERNAL_GOLOMB_BIT_LENGTH_TABLE_                      L"External golomb bit length table is not yet supported."
#define IDS_TVP_UNSUPPORTED_ENTROPY_CODING_METHOD_                                 L"Unsupported entropy coding method"
#define IDS_TVP_INVALID_TLG_HEADER_OR_VERSION_                                     L"Invalid TLG header or unsupported TLG version."
#define IDS_TVP_TLG_MALFORMED_TAG_MISSION_COLON_AFTER_NAME_LENGTH_                 L"Malformed TLG SDS tag structure, missing colon after name length"
#define IDS_TVP_TLG_MALFORMED_TAG_MISSION_EQUALS_AFTER_NAME_                       L"Malformed TLG SDS tag structure, missing equals after name"
#define IDS_TVP_TLG_MALFORMED_TAG_MISSION_COLON_AFTER_VAUE_LENGTH_                 L"Malformed TLG SDS tag structure, missing colon after value length"
#define IDS_TVP_TLG_MALFORMED_TAG_MISSION_COMMA_AFTER_TAG_                         L"Malformed TLG SDS tag structure, missing comma after a tag"
#define IDS_TVP_FILE_SIZE_IS_ZERO_                                                 L"File size is zero."
#define IDS_TVP_MEMORY_ALLOCATION_ERROR_                                           L"Memory allocation error."
#define IDS_TVP_FILE_READ_ERROR_                                                   L"File read error."
#define IDS_TVP_INVALID_PRERENDERED_FONT_FILE_                                     L"Signature not found or invalid pre-rendered font file."
#define IDS_TVP_NOT16BIT_UNICODE_FONT_FILE_                                        L"Not a 16-bit UNICODE font file."
#define IDS_TVP_INVALID_HEADER_VERSION_                                            L"Invalid header version."
#define IDS_TVP_TLG_INSUFFICIENT_MEMORY_                                           L"SaveTLG6: Insufficient memory"
#define IDS_TVP_TLG_TOO_LARGE_BIT_LENGTH_                                          L"SaveTLG6: Too large bit length (given image may be too large)"
#define IDS_TVP_CANNOT_RETRIVE_INTERFACE_FROM_DRAW_DEVICE                          L"Could not retrive interface from given draw device"
#define IDS_TVP_SCRIPT_EXCEPTION_RAISED_                                           L"Script exception raised"
#define IDS_TVP_HARDWARE_EXCEPTION_RAISED_                                         L"Hardware exception raised"
#define IDS_TVP_MAIN_CDPNAME_                                                      L"Script Editor (Main)"
#define IDS_TVP_EXCEPTION_CDPNAME_                                                 L"Script Editor (Exception)"
#define IDS_TVP_CANNNOT_LOCATE_UIDLLFOR_FOLDER_SELECTION_                          L"Not found krdevui.dll"
#define IDS_TVP_INVALID_UIDLL_                                                     L"Invalid krdevui.dll"
#define IDS_TVP_INVALID_BPP_                                                       L"Invalid bpp"
#define IDS_TVP_CANNOT_LOAD_PLUGIN_                                                L"Cannot load Plugin %1"
#define IDS_TVP_NOT_VALID_PLUGIN_                                                  L"Not valid plugin %1"
#define IDS_TVP_PLUGIN_UNINIT_FAILED_                                              L"Faild to release plugin"
#define IDS_TVP_CANNNOT_LINK_PLUGIN_WHILE_PLUGIN_LINKING_                          L"Cannot link plugin while plugin linking"
#define IDS_TVP_NOT_SUSIE_PLUGIN_                                                  L"Not Susie Plugin"
#define IDS_TVP_SUSIE_PLUGIN_ERROR_                                                L"Susie Plugin error : %1"
#define IDS_TVP_CANNOT_RELEASE_PLUGIN_                                             L"Cannot release plugin"
#define IDS_TVP_NOT_LOADED_PLUGIN_                                                 L"Not loaded plugin %1"
#define IDS_TVP_CANNOT_ALLOCATE_BITMAP_BITS_                                       L"Cannot allocate memory for Bitmap : %1 (size=%2)"
#define IDS_TVP_SCAN_LINE_RANGE_OVER_                                              L"Scan line %1 is range over (0 to %2)"
#define IDS_TVP_PLUGIN_ERROR_                                                      L"Plugin Error : %1"
#define IDS_TVP_INVALID_CDDADRIVE_                                                 L"Invalid CD-DA Drive"
#define IDS_TVP_CDDADRIVE_NOT_FOUND_                                               L"CD-DA Drive not found"
#define IDS_TVP_MCIERROR_                                                          L"MCI Error : %1"
#define IDS_TVP_INVALID_SMF_                                                       L"Invalid SMF : %1"
#define IDS_TVP_MALFORMED_MIDIMESSAGE_                                             L"Malformed MIDI Message"
#define IDS_TVP_CANNOT_INIT_DIRECT_SOUND_                                          L"DirectSound Initialize file : %1"
#define IDS_TVP_CANNOT_CREATE_DSSECONDARY_BUFFER_                                  L"Cannot create DirectSound secondary buffer : %1/%2"
#define IDS_TVP_INVALID_LOOP_INFORMATION_                                          L"Invalid loop information %1"
#define IDS_TVP_NOT_CHILD_MENU_ITEM_                                               L"Not child menu Item"
#define IDS_TVP_CANNOT_INIT_DIRECT3D_                                              L"Cannot initialize Direct3D : %1"
#define IDS_TVP_CANNOT_FIND_DISPLAY_MODE_                                          L"Cannot find display mode : %1"
#define IDS_TVP_CANNOT_SWITCH_TO_FULL_SCREEN_                                      L"Cannot switch to fullscreen : %1"
#define IDS_TVP_INVALID_PROPERTY_IN_FULL_SCREEN_                                   L"Invalid property in fullscreen : %1"
#define IDS_TVP_INVALID_METHOD_IN_FULL_SCREEN_                                     L"Invalid method in fullscreen : %1"
#define IDS_TVP_CANNOT_LOAD_CURSOR_                                                L"Cannot load mouse cursor : %1"
#define IDS_TVP_CANNOT_LOAD_KR_MOVIE_DLL_                                          L"Cannot load krmovie.dll"
#define IDS_TVP_INVALID_KR_MOVIE_DLL_                                              L"Invalid krmovie.dll"
#define IDS_TVP_ERROR_IN_KR_MOVIE_DLL_                                             L"Error in krmovie.dll : %1"
#define IDS_TVP_WINDOW_ALREADY_MISSING_                                            L"Window already missing"
#define IDS_TVP_PRERENDERED_FONT_MAPPING_FAILED_                                   L"Prerendered font mapping failed : %1"
#define IDS_TVP_CONFIG_FAIL_ORIGINAL_FILE_CANNOT_BE_REWRITTEN_                     L"Cannot write %1."
#define IDS_TVP_CONFIG_FAIL_TEMP_EXE_NOT_ERASED_                                   L"Did not exit %1. Cannot delete file."
#define IDS_TVP_EXECUTION_FAIL_                                                    L"Cannot execute %1."
#define IDS_TVP_PLUGIN_UNBOUND_FUNCTION_ERROR_                                     L"Plugin require %1 funcion. Bat not found function in this file."
#define IDS_TVP_EXCEPTION_HAD_BEEN_OCCURED_                                        L" = (Exception)"
#define IDS_TVP_CONSOLE_RESULT_                                                    L"Console : "
#define IDS_TVP_INFO_LISTING_FILES_                                                L"(info) Listing files in %1 …"
#define IDS_TVP_INFO_TOTAL_PHYSICAL_MEMORY_                                        L"(info) Total physical memory : %1"
#define IDS_TVP_INFO_SELECTED_PROJECT_DIRECTORY_                                   L"(info) Selected project directory : %1"
#define IDS_TVP_TOO_SMALL_EXECUTABLE_SIZE_                                         L"too small executable size."
#define IDS_TVP_INFO_LOADING_EXECUTABLE_EMBEDDED_OPTIONS_FAILED_                   L"(info) Loading executable embedded options failed (ignoring) : %1"
#define IDS_TVP_INFO_LOADING_EXECUTABLE_EMBEDDED_OPTIONS_SUCCEEDED_                L"(info) Loading executable embedded options succeeded."
#define IDS_TVP_FILE_NOT_FOUND_                                                    L"file not found."
#define IDS_TVP_INFO_LOADING_CONFIGURATION_FILE_FAILED_                            L"(info) Loading configuration file \"%1\" failed (ignoring) : %2"
#define IDS_TVP_INFO_LOADING_CONFIGURATION_FILE_SUCCEEDED_                         L"(info) Loading configuration file \"%1\" succeeded."
#define IDS_TVP_INFO_DATA_PATH_DOES_NOT_EXIST_TRYING_TO_MAKE_IT_                   L"(info) Data path does not exist, trying to make it ... %1"
#define IDS_TVP_OK_                                                                L"ok."
#define IDS_TVP_FAILD_                                                             L"failed."
#define IDS_TVP_INFO_DATA_PATH_                                                    L"(info) Data path : %1"
#define IDS_TVP_INFO_SPECIFIED_OPTION_EARLIER_ITEM_HAS_MORE_PRIORITY_              L"(info) Specified option(s) (earlier item has more priority) :"
#define IDS_TVP_NONE_                                                              L" (none)"
#define IDS_TVP_INFO_CPU_CLOCK_ROUGHLY_                                            L"(info) CPU clock (roughly) : %dMHz"
#define IDS_TVP_PROGRAM_STARTED_ON_                                                L"Program started on %1 (%2)"
#define IDS_TVP_KIRIKIRI_                                                          L"Kirikiri"
#define IDS_TVP_UNKNOWN_ERROR_                                                     L"Unknown error!"
#define IDS_TVP_EXIT_CODE_                                                         L"Exit code: %d\n"
#define IDS_TVP_FATAL_ERROR_                                                       L"Fatal Error"
#define IDS_TVP_ENABLE_DIGITIZER_                                                  L"Enable Digitizer"
#define IDS_TVP_TOUCH_INTEGRATED_TOUCH_                                            L"The device has an integrated touch digitizer. "
#define IDS_TVP_TOUCH_EXTERNAL_TOUCH_                                              L"The device has an external touch digitizer. "
#define IDS_TVP_TOUCH_INTEGRATED_PEN_                                              L"The device has an integrated pen digitizer."
#define IDS_TVP_TOUCH_EXTERNAL_PEN_                                                L"The device has an external pen digitizer."
#define IDS_TVP_TOUCH_MULTI_INPUT_                                                 L"The device supports multiple sources of digitizer input. "
#define IDS_TVP_TOUCH_READY_                                                       L"The device is ready to receive digitizer input."
#define IDS_TVP_CPU_CHECK_FAILURE_                                                 L"CPU check failure."
#define IDS_TVP_CPU_CHECK_FAILURE_CPU_FAMILY_OR_LESSER_IS_NOT_SUPPORTED_           L"CPU check failure: CPU family 4 or lesser is not supported\r\n%1"
#define IDS_TVP_INFO_CPU_NUMBER_                                                   L"(info) CPU #%1 : "
#define IDS_TVP_CPU_CHECK_FAILURE_NOT_SUPPRTED_CPU_                                L"CPU check failure: Not supported CPU\r\n%1"
#define IDS_TVP_INFO_FINALLY_DETECTED_CPU_FEATURES_                                L"(info) finally detected CPU features : %1"
#define IDS_TVP_CPU_CHECK_FAILURE_NOT_SUPPORTED_CPU_                               L"CPU check failure: Not supported CPU\r\n%1"
#define IDS_TVP_INFO_CPU_CLOCK_                                                    L"(info) CPU clock : %.1fMHz"
#define IDS_TVP_LAYER_BITMAP_BUFFER_UNDERRUN_DETECTED_CHECK_YOUR_DRAWING_CODE_     L"Layer bitmap: Buffer underrun detected. Check your drawing code!"
#define IDS_TVP_LAYER_BITMAP_BUFFER_OVERRUN_DETECTED_CHECK_YOUR_DRAWING_CODE_      L"Layer bitmap: Buffer overrun detected. Check your drawing code!"
#define IDS_TVP_FAILD_TO_CREATE_DIRECT3D_                                          L"Faild to create Direct3D9."
#define IDS_TVP_FAILD_TO_DECIDE_BACKBUFFER_FORMAT_                                 L"Faild to decide backbuffer format."
#define IDS_TVP_FAILD_TO_CREATE_DIRECT3DDEVICE_                                    L"Faild to create Direct3D9 Device."
#define IDS_TVP_FAILD_TO_SET_VIEWPORT_                                             L"Faild to set viewport."
#define IDS_TVP_FAILD_TO_SET_RENDER_STATE_                                         L"Faild to set render state."
#define IDS_TVP_WARNING_IMAGE_SIZE_TOO_LARGE_MAY_BE_CANNOT_CREATE_TEXTURE_         L"warning : Image size too large. May be cannot create texture."
#define IDS_TVP_USE_POWER_OF_TWO_SURFACE_                                          L"Use power of two surface."
#define IDS_TVP_CANNOT_ALLOCATE_D3DOFF_SCREEN_SURFACE_                             L"Cannot allocate D3D off-screen surface/HR=%1"
#define IDS_TVP_BASIC_DRAW_DEVICE_FAILED_TO_CREATE_DIRECT3DDEVICES_                L"BasicDrawDevice: Failed to create Direct3D devices: %1"
#define IDS_TVP_BASIC_DRAW_DEVICE_FAILED_TO_CREATE_DIRECT3DDEVICES_UNKNOWN_REASON_ L"BasicDrawDevice: Failed to create Direct3D devices: unknown reason"
#define IDS_TVP_BASIC_DRAW_DEVICE_TEXTURE_HAS_ALREADY_BEEN_LOCKED_                 L"BasicDrawDevice: Texture has already been locked (StartBitmapCompletion() has been called twice without EndBitmapCompletion()), unlocking the texture."
#define IDS_TVP_INTERNAL_ERROR_RESULT_                                             L"Internal error/HR=%1"
#define IDS_TVP_BASIC_DRAW_DEVICE_INF_POLYGON_DRAWING_FAILED_                      L"BasicDrawDevice: (inf) Polygon drawing failed/HR=%1"
#define IDS_TVP_BASIC_DRAW_DEVICE_INF_DIRECT3DDEVICE_PRESENT_FAILED_               L"BasicDrawDevice: (inf) IDirect3DDevice::Present failed/HR=%1"
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_RESTART_                L"ChangeDisplaySettings failed: DISP_CHANGE_RESTART"
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_BAD_FLAGS_              L"ChangeDisplaySettings failed: DISP_CHANGE_BADFLAGS"
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_BAD_PARAM_              L"ChangeDisplaySettings failed: DISP_CHANGE_BADPARAM"
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_FAILED_                 L"ChangeDisplaySettings failed: DISP_CHANGE_FAILED"
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_BAD_MODE_               L"ChangeDisplaySettings failed: DISP_CHANGE_BADMODE"
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_NOT_UPDATED_            L"ChangeDisplaySettings failed: DISP_CHANGE_NOTUPDATED"
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_UNKNOWN_REASON_                     L"ChangeDisplaySettings failed: unknown reason (%1)"
#define IDS_TVP_FAILED_TO_CREATE_SCREEN_DC_                                        L"Failed to create screen DC"
#define IDS_TVP_FAILED_TO_CREATE_OFFSCREEN_BITMAP_                                 L"Failed to create offscreen bitmap"
#define IDS_TVP_FAILED_TO_CREATE_OFFSCREEN_DC_                                     L"Failed to create offscreen DC"
#define IDS_TVP_INFO_SUSIE_PLUGIN_INFO_                                            L"(info) Susie plugin info : %1"
#define IDS_TVP_SUSIE_PLUGIN_UNSUPPORTED_BITMAP_HEADER_                            L"Non-supported bitmap header was given from susie plug-in."
#define IDS_TVP_BASIC_DRAW_DEVICE_FAILED_TO_CREATE_DIRECT3DDEVICE_                 L"BasicDrawDevice: Failed to create Direct3D Device: %1"
#define IDS_TVP_BASIC_DRAW_DEVICE_FAILED_TO_CREATE_DIRECT3DDEVICE_UNKNOWN_REASON_  L"BasicDrawDevice: Failed to create Direct3D Device: unknown reason"
#define IDS_TVP_COULD_NOT_CREATE_ANY_DRAW_DEVICE_                                  L"Fatal: Could not create any drawer objects."
#define IDS_TVP_BASIC_DRAW_DEVICE_DOES_NOT_SUPPORTE_LAYER_MANAGER_MORE_THAN_ONE_   L"\"basic draw\" device does not support layer manager more than 1"
#define IDS_TVP_INVALID_VIDEO_SIZE_                                                L"Invalid video size"
#define IDS_TVP_ROUGH_VSYNC_INTERVAL_READ_FROM_API_                                L"Rough VSync interval read from API : %1"
#define IDS_TVP_ROUGH_VSYNC_INTERVAL_STILL_SEEMS_WRONG_                            L"Rough VSync interval still seems wrong, assuming default value (16)"
#define IDS_TVP_INFO_FOUND_DIRECT3DINTERFACE_                                      L"(info) IDirect3D9 or higher detected. Retrieving current Direct3D driver information..."
#define IDS_TVP_INFO_FAILD_                                                        L"(info) Failed."
#define IDS_TVP_INFO_DIRECT3D_                                                     L"(info) Loading Direct3D ..."
#define IDS_TVP_CANNOT_LOAD_D3DDLL_                                                L"Cannot load d3d9.dll"
#define IDS_TVP_NOT_FOUND_DIRECT3DCREATE_                                          L"Missing Direct3DCreate9 in d3d9.dll"
#define IDS_TVP_INFO_ENVIRONMENT_USING_                                            L"(info) environment: using %1"
#define IDS_TVP_INFO_SEARCH_BEST_FULLSCREEN_RESOLUTION_                            L"(info) Searching best fullscreen resolution ..."
#define IDS_TVP_INFO_CONDITION_PREFERRED_SCREEN_MODE_                              L"(info) condition: preferred screen mode: %1"
#define IDS_TVP_INFO_CONDITION_MODE_                                               L"(info) condition: mode: %1"
#define IDS_TVP_INFO_CONDITION_ZOOM_MODE_                                          L"(info) condition: zoom mode: %1"
#define IDS_TVP_INFO_ENVIRONMENT_DEFAULT_SCREEN_MODE_                              L"(info) environment: default screen mode: %1"
#define IDS_TVP_INFO_ENVIRONMENT_DEFAULT_SCREEN_ASPECT_RATIO_                      L"(info) environment: default screen aspect ratio: %1 : %2"
#define IDS_TVP_INFO_ENVIRONMENT_AVAILABLE_DISPLAY_MODES_                          L"(info) environment: available display modes:"
#define IDS_TVP_INFO_NOT_FOUND_SCREEN_MODE_FROM_DRIVER_                            L"(info) Panic! There is no reasonable candidate screen mode provided from the driver ... trying to use the default screen size and color depth ..."
#define IDS_TVP_INFO_RESULT_CANDIDATES_                                            L"(info) result: candidates:"
#define IDS_TVP_INFO_TRY_SCREEN_MODE_                                              L"(info) Trying screen mode: %1"
#define IDS_TVP_ALL_SCREEN_MODE_ERROR_                                             L"All screen mode has been tested, but no modes available at all."
#define IDS_TVP_INFO_CHANGE_SCREEN_MODE_SUCCESS_                                   L"(info) Changing screen mode succeeded"
#define IDS_TVP_SELECT_XP3FILE_OR_FOLDER_                                          L"Select XP3 file or folder"
#define IDS_TVP_D3D_ERR_DEVICE_LOST_                                               L"D3D : The device has been lost but cannot be reset at this time."
#define IDS_TVP_D3D_ERR_DRIVER_IINTERNAL_ERROR_                                    L"D3D : Internal driver error. Applications should destroy and recreate the device when receiving this error. "
#define IDS_TVP_D3D_ERR_INVALID_CALL_                                              L"D3D : The method call is invalid. For example, a method\'s parameter may not be a valid pointer."
#define IDS_TVP_D3D_ERR_OUT_OF_VIDEO_MEMORY_                                       L"D3D : Direct3D does not have enough display memory to perform the operation. "
#define IDS_TVP_D3D_ERR_OUT_OF_MEMORY_                                             L"D3D : Direct3D could not allocate sufficient memory to complete the call."
#define IDS_TVP_D3D_ERR_WRONG_TEXTURE_FORMAT_                                      L"D3D : The pixel format of the texture surface is not valid."
#define IDS_TVP_D3D_ERR_UNSUPORTED_COLOR_OPERATION_                                L"D3D : The device does not support a specified texture-blending operation for color values."
#define IDS_TVP_D3D_ERR_UNSUPORTED_COLOR_ARG_                                      L"D3D : The device does not support a specified texture-blending argument for color values."
#define IDS_TVP_D3D_ERR_UNSUPORTED_AALPHT_OPERATION_                               L"D3D : The device does not support a specified texture-blending operation for the alpha channel."
#define IDS_TVP_D3D_ERR_UNSUPORTED_ALPHA_ARG_                                      L"D3D : The device does not support a specified texture-blending argument for the alpha channel."
#define IDS_TVP_D3D_ERR_TOO_MANY_OPERATIONS_                                       L"D3D : The application is requesting more texture-filtering operations than the device supports."
#define IDS_TVP_D3D_ERR_CONFLICTIONING_TEXTURE_FILTER_                             L"D3D : The current texture filters cannot be used together."
#define IDS_TVP_D3D_ERR_UNSUPORTED_FACTOR_VALUE_                                   L"D3D : The device does not support the specified texture factor value. Not used provided only to support older drivers."
#define IDS_TVP_D3D_ERR_CONFLICTIONING_RENDER_STATE_                               L"D3D : The currently set render states cannot be used together."
#define IDS_TVP_D3D_ERR_UNSUPPORTED_TEXTURE_FILTER_                                L"D3D : The device does not support the specified texture filter."
#define IDS_TVP_D3D_ERR_CONFLICTIONING_TEXTURE_PALETTE_                            L"D3D : The current textures cannot be used simultaneously."
#define IDS_TVP_D3D_ERR_NOT_FOUND_                                                 L"D3D : The requested item was not found."
#define IDS_TVP_D3D_ERR_MORE_DATA_                                                 L"D3D : There is more data available than the specified buffer size can hold."
#define IDS_TVP_D3D_ERR_DEVICE_NOT_RESET_                                          L"D3D : The device has been lost but can be reset at this time."
#define IDS_TVP_D3D_ERR_NOT_AVAILABLE_                                             L"D3D : This device does not support the queried technique."
#define IDS_TVP_D3D_ERR_INVALID_DEVICE_                                            L"D3D : The requested device type is not valid."
#define IDS_TVP_D3D_ERR_DRIVER_INVALID_CALL_                                       L"D3D : Not used."
#define IDS_TVP_D3D_ERR_WAS_STILL_DRAWING_                                         L"D3D : The previous blit operation that is transferring information to or from this surface is incomplete."
#define IDS_TVP_D3D_ERR_DEVICE_HUNG_                                               L"D3D : The device that returned this code caused the hardware adapter to be reset by the OS."
#define IDS_TVP_D3D_ERR_UNSUPPORTED_OVERLAY_                                       L"D3D : The device does not support overlay for the specified size or display mode. "
#define IDS_TVP_D3D_ERR_UNSUPPORTED_OVERLAY_FORMAT_                                L"D3D : The device does not support overlay for the specified surface format. "
#define IDS_TVP_D3D_ERR_CANNOT_PROTECT_CONTENT_                                    L"D3D : The specified content cannot be protected."
#define IDS_TVP_D3D_ERR_UNSUPPORTED_CRYPTO_                                        L"D3D : The specified cryptographic algorithm is not supported."
#define IDS_TVP_D3D_ERR_PRESENT_STATISTICS_DIS_JOINT_                              L"D3D : The present statistics have no orderly sequence."
#define IDS_TVP_D3D_ERR_DEVICE_REMOVED_                                            L"D3D : The hardware adapter has been removed."
#define IDS_TVP_D3D_OK_NO_AUTO_GEN_                                                L"D3D : This is a success code. However, the autogeneration of mipmaps is not supported for this format."
#define IDS_TVP_D3D_ERR_FAIL_                                                      L"D3D : An undetermined error occurred inside the Direct3D subsystem."
#define IDS_TVP_D3D_ERR_INVALID_ARG_                                               L"D3D : An invalid parameter was passed to the returning function."
#define IDS_TVP_D3D_UNKNOWN_ERROR_                                                 L"D3D : Unknown error."
#define IDS_TVP_EXCEPTION_ACCESS_VIOLATION_                                        L"Access Violation: The thread attempts to read from or write to a virtual address for which it does not have access."
#define IDS_TVP_EXCEPTION_BREAKPOINT_                                              L"Break Point: A breakpoint is encountered."
#define IDS_TVP_EXCEPTION_DATATYPE_MISALIGNMENT_                                   L"Data Type Misalignment: The thread attempts to read or write data that is misaligned on hardware that does not provide alignment. For example, 16-bit values must be aligned on 2-byte boundaries, 32-bit values on 4-byte boundaries, and so on."
#define IDS_TVP_EXCEPTION_SINGLE_STEP_                                             L"Single Step: A trace trap or other single instruction mechanism signals that one instruction is executed."
#define IDS_TVP_EXCEPTION_ARRAY_BOUNDS_EXCEEDED_                                   L"Array Bounds Exceede: The thread attempts to access an array element that is out of bounds, and the underlying hardware supports bounds checking."
#define IDS_TVP_EXCEPTION_FLT_DENORMAL_OPERAND_                                    L"Denormal Operand: One of the operands in a floating point operation is denormal. A denormal value is one that is too small to represent as a standard floating point value."
#define IDS_TVP_EXCEPTION_FLT_DIVIDE_BY_ZERO_                                      L"Divide By Zero: The thread attempts to divide a floating point value by a floating point divisor of 0 (zero)."
#define IDS_TVP_EXCEPTION_FLT_INEXACT_RESULT_                                      L"Inexact Result: The result of a floating point operation cannot be represented exactly as a decimal fraction."
#define IDS_TVP_EXCEPTION_FLT_INVALID_OPERATION_                                   L"Invalid Operation: A floating point exception that is not included in this list."
#define IDS_TVP_EXCEPTION_FLT_OVERFLOW_                                            L"Overflow: The exponent of a floating point operation is greater than the magnitude allowed by the corresponding type."
#define IDS_TVP_EXCEPTION_FLT_STACK_CHECK_                                         L"Stack Check: The stack has overflowed or underflowed, because of a floating point operation."
#define IDS_TVP_EXCEPTION_FLT_UNDERFLOW_                                           L"Underflow: The exponent of a floating point operation is less than the magnitude allowed by the corresponding type."
#define IDS_TVP_EXCEPTION_INT_DIVIDE_BY_ZERO_                                      L"Divide By Zero: The thread attempts to divide an integer value by an integer divisor of 0 (zero)."
#define IDS_TVP_EXCEPTION_INT_OVERFLOW_                                            L"Overflow: The result of an integer operation creates a value that is too large to be held by the destination register. In some cases, this will result in a carry out of the most significant bit of the result. Some operations do not set the carry flag."
#define IDS_TVP_EXCEPTION_PRIV_INSTRUCTION_                                        L"Priv Instruction: The thread attempts to execute an instruction with an operation that is not allowed in the current computer mode."
#define IDS_TVP_EXCEPTION_NONCONTINUABLE_EXCEPTION_                                L"Noncontinuable Exception: The thread attempts to continue execution after a non-continuable exception occurs."
#define IDS_TVP_EXCEPTION_GUARD_PAGE_                                              L"Guard Page: The thread accessed memory allocated with the PAGE_GUARD modifier."
#define IDS_TVP_EXCEPTION_ILLEGAL_INSTRUCTION_                                     L"Illegal Instruction: The thread tries to execute an invalid instruction."
#define IDS_TVP_EXCEPTION_IN_PAGE_ERROR_                                           L"In Page Error: The thread tries to access a page that is not present, and the system is unable to load the page. For example, this exception might occur if a network connection is lost while running a program over a network."
#define IDS_TVP_EXCEPTION_INVALID_DISPOSITION_                                     L"Invalid Disposition: An exception handler returns an invalid disposition to the exception dispatcher. Programmers using a high-level language such as C should never encounter this exception."
#define IDS_TVP_EXCEPTION_INVALID_HANDLE_                                          L"Invalid Handle: The thread used a handle to a kernel object that was invalid (probably because it had been closed.)"
#define IDS_TVP_EXCEPTION_STACK_OVERFLOW_                                          L"Stack Overflow: The thread uses up its stack."
#define IDS_TVP_EXCEPTION_UNWIND_CCONSOLIDATE_                                     L"Unwind Consolidate: A frame consolidation has been executed."
#define IDS_TVP_CANNOT_SHOW_MODAL_AREADY_SHOWED_                                   L"Cannot Show Modal."
#define IDS_TVP_CANNOT_SHOW_MODAL_SINGLE_WINDOW                                    L"Cannot Show Modal. When it is single window."
#define IDS_TVP_UNKNOW_QT_ERROR                                                    L"Unkonw Qt Error"
#endif
